// ---------------------------------------------------------------------------
// Customers mock data — 30 customers
// ---------------------------------------------------------------------------

import { avatarImage } from "./images";

// ---- Types ----------------------------------------------------------------

export interface Address {
  street: string;
  city: string;
  state: string;
  zip: string;
  country: string;
}

export interface Customer {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  avatar: string;
  address: Address;
  shippingAddress: Address;
  orderCount: number;
  totalSpent: number;
  createdAt: string;
  lastOrderAt: string | null;
  tags: string[];
  notes: string;
}

// ---- Data -----------------------------------------------------------------

export const customers: Customer[] = [
  {
    id: "cust-001",
    firstName: "Sarah",
    lastName: "Mitchell",
    email: "sarah.mitchell@email.com",
    phone: "(415) 555-0101",
    avatar: avatarImage("sarah-mitchell"),
    address: { street: "742 Evergreen Terrace", city: "San Francisco", state: "CA", zip: "94102", country: "US" },
    shippingAddress: { street: "742 Evergreen Terrace", city: "San Francisco", state: "CA", zip: "94102", country: "US" },
    orderCount: 8,
    totalSpent: 12450,
    createdAt: "2024-06-15T10:00:00Z",
    lastOrderAt: "2025-12-05T14:30:00Z",
    tags: ["vip", "repeat-buyer"],
    notes: "Prefers white-glove delivery. Interested in mid-century modern.",
  },
  {
    id: "cust-002",
    firstName: "James",
    lastName: "Rodriguez",
    email: "james.rodriguez@email.com",
    phone: "(212) 555-0102",
    avatar: avatarImage("james-rodriguez"),
    address: { street: "1600 Broadway", city: "New York", state: "NY", zip: "10019", country: "US" },
    shippingAddress: { street: "1600 Broadway", city: "New York", state: "NY", zip: "10019", country: "US" },
    orderCount: 5,
    totalSpent: 8920,
    createdAt: "2024-08-20T10:00:00Z",
    lastOrderAt: "2025-11-18T09:15:00Z",
    tags: ["repeat-buyer"],
    notes: "Apartment building, buzzer code 4A.",
  },
  {
    id: "cust-003",
    firstName: "Emily",
    lastName: "Chen",
    email: "emily.chen@email.com",
    phone: "(310) 555-0103",
    avatar: avatarImage("emily-chen"),
    address: { street: "8833 Sunset Blvd", city: "Los Angeles", state: "CA", zip: "90069", country: "US" },
    shippingAddress: { street: "8833 Sunset Blvd", city: "Los Angeles", state: "CA", zip: "90069", country: "US" },
    orderCount: 12,
    totalSpent: 24680,
    createdAt: "2024-03-10T10:00:00Z",
    lastOrderAt: "2025-12-10T16:45:00Z",
    tags: ["vip", "repeat-buyer", "interior-designer"],
    notes: "Interior designer. Often buys for clients. Trade discount applied.",
  },
  {
    id: "cust-004",
    firstName: "Michael",
    lastName: "Thompson",
    email: "m.thompson@email.com",
    phone: "(773) 555-0104",
    avatar: avatarImage("michael-thompson"),
    address: { street: "233 N Michigan Ave", city: "Chicago", state: "IL", zip: "60601", country: "US" },
    shippingAddress: { street: "233 N Michigan Ave", city: "Chicago", state: "IL", zip: "60601", country: "US" },
    orderCount: 3,
    totalSpent: 4250,
    createdAt: "2025-01-05T10:00:00Z",
    lastOrderAt: "2025-10-22T11:00:00Z",
    tags: [],
    notes: "",
  },
  {
    id: "cust-005",
    firstName: "Olivia",
    lastName: "Williams",
    email: "olivia.w@email.com",
    phone: "(503) 555-0105",
    avatar: avatarImage("olivia-williams"),
    address: { street: "1001 NW Lovejoy St", city: "Portland", state: "OR", zip: "97209", country: "US" },
    shippingAddress: { street: "1001 NW Lovejoy St", city: "Portland", state: "OR", zip: "97209", country: "US" },
    orderCount: 6,
    totalSpent: 9870,
    createdAt: "2024-09-22T10:00:00Z",
    lastOrderAt: "2025-11-30T13:20:00Z",
    tags: ["repeat-buyer"],
    notes: "Prefers sustainable/eco-friendly products.",
  },
  {
    id: "cust-006",
    firstName: "Daniel",
    lastName: "Kim",
    email: "daniel.kim@email.com",
    phone: "(206) 555-0106",
    avatar: avatarImage("daniel-kim"),
    address: { street: "456 Pike St", city: "Seattle", state: "WA", zip: "98101", country: "US" },
    shippingAddress: { street: "456 Pike St", city: "Seattle", state: "WA", zip: "98101", country: "US" },
    orderCount: 2,
    totalSpent: 2650,
    createdAt: "2025-04-18T10:00:00Z",
    lastOrderAt: "2025-09-14T10:00:00Z",
    tags: [],
    notes: "Condo, freight elevator available weekdays only.",
  },
  {
    id: "cust-007",
    firstName: "Jessica",
    lastName: "Patel",
    email: "jpatel@email.com",
    phone: "(512) 555-0107",
    avatar: avatarImage("jessica-patel"),
    address: { street: "2020 Congress Ave", city: "Austin", state: "TX", zip: "78701", country: "US" },
    shippingAddress: { street: "2020 Congress Ave", city: "Austin", state: "TX", zip: "78701", country: "US" },
    orderCount: 4,
    totalSpent: 5630,
    createdAt: "2024-11-30T10:00:00Z",
    lastOrderAt: "2025-11-05T15:40:00Z",
    tags: ["repeat-buyer"],
    notes: "",
  },
  {
    id: "cust-008",
    firstName: "Robert",
    lastName: "Johnson",
    email: "rob.johnson@email.com",
    phone: "(305) 555-0108",
    avatar: avatarImage("robert-johnson"),
    address: { street: "1200 Brickell Ave", city: "Miami", state: "FL", zip: "33131", country: "US" },
    shippingAddress: { street: "1200 Brickell Ave", city: "Miami", state: "FL", zip: "33131", country: "US" },
    orderCount: 7,
    totalSpent: 15890,
    createdAt: "2024-05-08T10:00:00Z",
    lastOrderAt: "2025-12-08T10:30:00Z",
    tags: ["vip", "repeat-buyer"],
    notes: "Has a vacation home. Sometimes ships to alternate address in Key West.",
  },
  {
    id: "cust-009",
    firstName: "Amanda",
    lastName: "Davis",
    email: "amanda.davis@email.com",
    phone: "(303) 555-0109",
    avatar: avatarImage("amanda-davis"),
    address: { street: "1515 Larimer St", city: "Denver", state: "CO", zip: "80202", country: "US" },
    shippingAddress: { street: "1515 Larimer St", city: "Denver", state: "CO", zip: "80202", country: "US" },
    orderCount: 1,
    totalSpent: 1899,
    createdAt: "2025-10-01T10:00:00Z",
    lastOrderAt: "2025-10-01T10:00:00Z",
    tags: ["new-customer"],
    notes: "",
  },
  {
    id: "cust-010",
    firstName: "Chris",
    lastName: "Martinez",
    email: "chris.martinez@email.com",
    phone: "(602) 555-0110",
    avatar: avatarImage("chris-martinez"),
    address: { street: "100 W Washington St", city: "Phoenix", state: "AZ", zip: "85003", country: "US" },
    shippingAddress: { street: "100 W Washington St", city: "Phoenix", state: "AZ", zip: "85003", country: "US" },
    orderCount: 9,
    totalSpent: 18320,
    createdAt: "2024-02-14T10:00:00Z",
    lastOrderAt: "2025-12-12T08:00:00Z",
    tags: ["vip", "repeat-buyer"],
    notes: "Furnishing a new home. Multiple rooms in progress.",
  },
  {
    id: "cust-011",
    firstName: "Lauren",
    lastName: "Baker",
    email: "lauren.baker@email.com",
    phone: "(615) 555-0111",
    avatar: avatarImage("lauren-baker"),
    address: { street: "505 Broadway", city: "Nashville", state: "TN", zip: "37203", country: "US" },
    shippingAddress: { street: "505 Broadway", city: "Nashville", state: "TN", zip: "37203", country: "US" },
    orderCount: 3,
    totalSpent: 3750,
    createdAt: "2025-02-28T10:00:00Z",
    lastOrderAt: "2025-08-15T14:00:00Z",
    tags: [],
    notes: "",
  },
  {
    id: "cust-012",
    firstName: "Andrew",
    lastName: "Wilson",
    email: "a.wilson@email.com",
    phone: "(404) 555-0112",
    avatar: avatarImage("andrew-wilson"),
    address: { street: "285 Peachtree Center Ave", city: "Atlanta", state: "GA", zip: "30303", country: "US" },
    shippingAddress: { street: "285 Peachtree Center Ave", city: "Atlanta", state: "GA", zip: "30303", country: "US" },
    orderCount: 4,
    totalSpent: 6290,
    createdAt: "2024-10-12T10:00:00Z",
    lastOrderAt: "2025-10-30T12:15:00Z",
    tags: ["repeat-buyer"],
    notes: "",
  },
  {
    id: "cust-013",
    firstName: "Megan",
    lastName: "Taylor",
    email: "megan.t@email.com",
    phone: "(617) 555-0113",
    avatar: avatarImage("megan-taylor"),
    address: { street: "800 Boylston St", city: "Boston", state: "MA", zip: "02199", country: "US" },
    shippingAddress: { street: "800 Boylston St", city: "Boston", state: "MA", zip: "02199", country: "US" },
    orderCount: 2,
    totalSpent: 2890,
    createdAt: "2025-05-20T10:00:00Z",
    lastOrderAt: "2025-09-22T16:30:00Z",
    tags: [],
    notes: "Third-floor walkup, no elevator.",
  },
  {
    id: "cust-014",
    firstName: "David",
    lastName: "Lee",
    email: "david.lee@email.com",
    phone: "(202) 555-0114",
    avatar: avatarImage("david-lee"),
    address: { street: "1330 Maryland Ave", city: "Washington", state: "DC", zip: "20024", country: "US" },
    shippingAddress: { street: "1330 Maryland Ave", city: "Washington", state: "DC", zip: "20024", country: "US" },
    orderCount: 6,
    totalSpent: 11540,
    createdAt: "2024-07-03T10:00:00Z",
    lastOrderAt: "2025-11-25T11:45:00Z",
    tags: ["vip", "repeat-buyer"],
    notes: "",
  },
  {
    id: "cust-015",
    firstName: "Rachel",
    lastName: "Green",
    email: "rachel.g@email.com",
    phone: "(612) 555-0115",
    avatar: avatarImage("rachel-green"),
    address: { street: "250 Marquette Ave", city: "Minneapolis", state: "MN", zip: "55401", country: "US" },
    shippingAddress: { street: "250 Marquette Ave", city: "Minneapolis", state: "MN", zip: "55401", country: "US" },
    orderCount: 1,
    totalSpent: 699,
    createdAt: "2025-11-10T10:00:00Z",
    lastOrderAt: "2025-11-10T10:00:00Z",
    tags: ["new-customer"],
    notes: "",
  },
  {
    id: "cust-016",
    firstName: "Jason",
    lastName: "Brown",
    email: "jason.brown@email.com",
    phone: "(619) 555-0116",
    avatar: avatarImage("jason-brown"),
    address: { street: "750 B St", city: "San Diego", state: "CA", zip: "92101", country: "US" },
    shippingAddress: { street: "750 B St", city: "San Diego", state: "CA", zip: "92101", country: "US" },
    orderCount: 5,
    totalSpent: 7840,
    createdAt: "2024-12-01T10:00:00Z",
    lastOrderAt: "2025-11-20T09:30:00Z",
    tags: ["repeat-buyer"],
    notes: "",
  },
  {
    id: "cust-017",
    firstName: "Nicole",
    lastName: "Anderson",
    email: "nicole.a@email.com",
    phone: "(704) 555-0117",
    avatar: avatarImage("nicole-anderson"),
    address: { street: "200 E Trade St", city: "Charlotte", state: "NC", zip: "28202", country: "US" },
    shippingAddress: { street: "200 E Trade St", city: "Charlotte", state: "NC", zip: "28202", country: "US" },
    orderCount: 2,
    totalSpent: 3198,
    createdAt: "2025-06-15T10:00:00Z",
    lastOrderAt: "2025-10-08T14:20:00Z",
    tags: [],
    notes: "",
  },
  {
    id: "cust-018",
    firstName: "Brian",
    lastName: "White",
    email: "brian.white@email.com",
    phone: "(702) 555-0118",
    avatar: avatarImage("brian-white"),
    address: { street: "3570 Las Vegas Blvd", city: "Las Vegas", state: "NV", zip: "89109", country: "US" },
    shippingAddress: { street: "3570 Las Vegas Blvd", city: "Las Vegas", state: "NV", zip: "89109", country: "US" },
    orderCount: 3,
    totalSpent: 4570,
    createdAt: "2025-03-08T10:00:00Z",
    lastOrderAt: "2025-08-28T10:00:00Z",
    tags: [],
    notes: "Gated community, needs gate code for delivery.",
  },
  {
    id: "cust-019",
    firstName: "Sophia",
    lastName: "Garcia",
    email: "sophia.garcia@email.com",
    phone: "(210) 555-0119",
    avatar: avatarImage("sophia-garcia"),
    address: { street: "300 E Commerce St", city: "San Antonio", state: "TX", zip: "78205", country: "US" },
    shippingAddress: { street: "300 E Commerce St", city: "San Antonio", state: "TX", zip: "78205", country: "US" },
    orderCount: 7,
    totalSpent: 13250,
    createdAt: "2024-04-20T10:00:00Z",
    lastOrderAt: "2025-12-01T12:00:00Z",
    tags: ["vip", "repeat-buyer"],
    notes: "Refers friends frequently. Ambassador potential.",
  },
  {
    id: "cust-020",
    firstName: "Kevin",
    lastName: "Harris",
    email: "kevin.h@email.com",
    phone: "(469) 555-0120",
    avatar: avatarImage("kevin-harris"),
    address: { street: "2011 Commerce St", city: "Dallas", state: "TX", zip: "75201", country: "US" },
    shippingAddress: { street: "2011 Commerce St", city: "Dallas", state: "TX", zip: "75201", country: "US" },
    orderCount: 1,
    totalSpent: 899,
    createdAt: "2025-12-01T10:00:00Z",
    lastOrderAt: "2025-12-01T10:00:00Z",
    tags: ["new-customer"],
    notes: "",
  },
  {
    id: "cust-021",
    firstName: "Ashley",
    lastName: "Clark",
    email: "ashley.clark@email.com",
    phone: "(804) 555-0121",
    avatar: avatarImage("ashley-clark"),
    address: { street: "919 E Main St", city: "Richmond", state: "VA", zip: "23219", country: "US" },
    shippingAddress: { street: "919 E Main St", city: "Richmond", state: "VA", zip: "23219", country: "US" },
    orderCount: 4,
    totalSpent: 5980,
    createdAt: "2024-11-05T10:00:00Z",
    lastOrderAt: "2025-10-15T15:00:00Z",
    tags: ["repeat-buyer"],
    notes: "",
  },
  {
    id: "cust-022",
    firstName: "Matthew",
    lastName: "Lewis",
    email: "matt.lewis@email.com",
    phone: "(314) 555-0122",
    avatar: avatarImage("matthew-lewis"),
    address: { street: "1 S Broadway", city: "St. Louis", state: "MO", zip: "63102", country: "US" },
    shippingAddress: { street: "1 S Broadway", city: "St. Louis", state: "MO", zip: "63102", country: "US" },
    orderCount: 2,
    totalSpent: 2748,
    createdAt: "2025-07-22T10:00:00Z",
    lastOrderAt: "2025-09-30T10:00:00Z",
    tags: [],
    notes: "",
  },
  {
    id: "cust-023",
    firstName: "Stephanie",
    lastName: "Walker",
    email: "steph.walker@email.com",
    phone: "(919) 555-0123",
    avatar: avatarImage("stephanie-walker"),
    address: { street: "330 Fayetteville St", city: "Raleigh", state: "NC", zip: "27601", country: "US" },
    shippingAddress: { street: "330 Fayetteville St", city: "Raleigh", state: "NC", zip: "27601", country: "US" },
    orderCount: 3,
    totalSpent: 4120,
    createdAt: "2025-01-18T10:00:00Z",
    lastOrderAt: "2025-07-20T11:30:00Z",
    tags: [],
    notes: "",
  },
  {
    id: "cust-024",
    firstName: "Ryan",
    lastName: "Hall",
    email: "ryan.hall@email.com",
    phone: "(503) 555-0124",
    avatar: avatarImage("ryan-hall"),
    address: { street: "1120 NW Couch St", city: "Portland", state: "OR", zip: "97209", country: "US" },
    shippingAddress: { street: "1120 NW Couch St", city: "Portland", state: "OR", zip: "97209", country: "US" },
    orderCount: 10,
    totalSpent: 22340,
    createdAt: "2024-01-30T10:00:00Z",
    lastOrderAt: "2025-12-10T14:00:00Z",
    tags: ["vip", "repeat-buyer"],
    notes: "Long-time customer. Furnished entire home through FSOW.",
  },
  {
    id: "cust-025",
    firstName: "Natalie",
    lastName: "Young",
    email: "natalie.young@email.com",
    phone: "(407) 555-0125",
    avatar: avatarImage("natalie-young"),
    address: { street: "400 W Church St", city: "Orlando", state: "FL", zip: "32801", country: "US" },
    shippingAddress: { street: "400 W Church St", city: "Orlando", state: "FL", zip: "32801", country: "US" },
    orderCount: 2,
    totalSpent: 3390,
    createdAt: "2025-08-05T10:00:00Z",
    lastOrderAt: "2025-11-12T10:00:00Z",
    tags: [],
    notes: "",
  },
  {
    id: "cust-026",
    firstName: "Tyler",
    lastName: "Allen",
    email: "tyler.allen@email.com",
    phone: "(801) 555-0126",
    avatar: avatarImage("tyler-allen"),
    address: { street: "111 S Main St", city: "Salt Lake City", state: "UT", zip: "84111", country: "US" },
    shippingAddress: { street: "111 S Main St", city: "Salt Lake City", state: "UT", zip: "84111", country: "US" },
    orderCount: 1,
    totalSpent: 799,
    createdAt: "2025-11-28T10:00:00Z",
    lastOrderAt: "2025-11-28T10:00:00Z",
    tags: ["new-customer"],
    notes: "",
  },
  {
    id: "cust-027",
    firstName: "Hannah",
    lastName: "Scott",
    email: "hannah.scott@email.com",
    phone: "(412) 555-0127",
    avatar: avatarImage("hannah-scott"),
    address: { street: "600 Grant St", city: "Pittsburgh", state: "PA", zip: "15219", country: "US" },
    shippingAddress: { street: "600 Grant St", city: "Pittsburgh", state: "PA", zip: "15219", country: "US" },
    orderCount: 5,
    totalSpent: 8450,
    createdAt: "2024-08-15T10:00:00Z",
    lastOrderAt: "2025-11-08T16:00:00Z",
    tags: ["repeat-buyer"],
    notes: "",
  },
  {
    id: "cust-028",
    firstName: "Brandon",
    lastName: "King",
    email: "brandon.king@email.com",
    phone: "(901) 555-0128",
    avatar: avatarImage("brandon-king"),
    address: { street: "150 Peabody Pl", city: "Memphis", state: "TN", zip: "38103", country: "US" },
    shippingAddress: { street: "150 Peabody Pl", city: "Memphis", state: "TN", zip: "38103", country: "US" },
    orderCount: 3,
    totalSpent: 4690,
    createdAt: "2025-02-10T10:00:00Z",
    lastOrderAt: "2025-09-18T13:00:00Z",
    tags: [],
    notes: "",
  },
  {
    id: "cust-029",
    firstName: "Kayla",
    lastName: "Wright",
    email: "kayla.wright@email.com",
    phone: "(858) 555-0129",
    avatar: avatarImage("kayla-wright"),
    address: { street: "1250 Prospect St", city: "La Jolla", state: "CA", zip: "92037", country: "US" },
    shippingAddress: { street: "1250 Prospect St", city: "La Jolla", state: "CA", zip: "92037", country: "US" },
    orderCount: 6,
    totalSpent: 14200,
    createdAt: "2024-06-28T10:00:00Z",
    lastOrderAt: "2025-12-05T10:00:00Z",
    tags: ["vip", "repeat-buyer"],
    notes: "Beach house furnishing project.",
  },
  {
    id: "cust-030",
    firstName: "Marcus",
    lastName: "Hill",
    email: "marcus.hill@email.com",
    phone: "(312) 555-0130",
    avatar: avatarImage("marcus-hill"),
    address: { street: "875 N Michigan Ave", city: "Chicago", state: "IL", zip: "60611", country: "US" },
    shippingAddress: { street: "875 N Michigan Ave", city: "Chicago", state: "IL", zip: "60611", country: "US" },
    orderCount: 4,
    totalSpent: 7250,
    createdAt: "2024-09-10T10:00:00Z",
    lastOrderAt: "2025-11-28T09:00:00Z",
    tags: ["repeat-buyer"],
    notes: "High-rise condo, loading dock available.",
  },
];

// ---- Lookup helpers -------------------------------------------------------

export function getCustomerById(id: string): Customer | undefined {
  return customers.find((c) => c.id === id);
}

export function getCustomerByEmail(email: string): Customer | undefined {
  return customers.find((c) => c.email === email);
}

export function getVipCustomers(): Customer[] {
  return customers.filter((c) => c.tags.includes("vip"));
}

export function getCustomersByTag(tag: string): Customer[] {
  return customers.filter((c) => c.tags.includes(tag));
}

export const customerIds = customers.map((c) => c.id);
