// ---------------------------------------------------------------------------
// Products mock data — 50 products across 6 categories
// ---------------------------------------------------------------------------

import { productImage, productThumb, productGallery } from "./images";

// ---- Types ----------------------------------------------------------------

export type ProductStatus = "active" | "draft" | "archived";

export interface ProductVariant {
  id: string;
  name: string;
  type: "color" | "size" | "material";
  value: string;
  priceModifier: number; // added to base price
  stock: number;
  sku: string;
}

export interface ProductSpec {
  label: string;
  value: string;
}

export interface Product {
  id: string;
  name: string;
  slug: string;
  description: string;
  shortDescription: string;
  price: number;
  compareAtPrice: number | null;
  categoryId: string;
  subcategoryId: string;
  status: ProductStatus;
  featured: boolean;
  tags: string[];
  images: string[];
  thumbnail: string;
  variants: ProductVariant[];
  specs: ProductSpec[];
  stock: number;
  rating: number;
  reviewCount: number;
  weight: number; // in lbs
  dimensions: { width: number; height: number; depth: number }; // in inches
  sku: string;
  createdAt: string;
  updatedAt: string;
}

// ---- Helper ---------------------------------------------------------------

let _variantCounter = 0;
function vid(): string {
  _variantCounter += 1;
  return `var-${String(_variantCounter).padStart(4, "0")}`;
}

// ---- Products -------------------------------------------------------------

export const products: Product[] = [
  // ===== LIVING ROOM =====
  {
    id: "prod-001",
    name: "Modern Sofa",
    slug: "modern-sofa",
    description:
      "A clean-lined contemporary sofa upholstered in premium performance fabric. Features deep seats, solid hardwood frame, and sinuous spring suspension for lasting comfort. Removable cushion covers make cleaning a breeze.",
    shortDescription: "Clean-lined contemporary sofa with deep seating and performance fabric.",
    price: 1899,
    compareAtPrice: 2299,
    categoryId: "cat-living-room",
    subcategoryId: "sub-sofas",
    status: "active",
    featured: true,
    tags: ["bestseller", "new-arrival", "free-shipping"],
    images: productGallery("modern-sofa"),
    thumbnail: productThumb("modern-sofa"),
    variants: [
      { id: vid(), name: "Light Gray", type: "color", value: "#D3D3D3", priceModifier: 0, stock: 12, sku: "MS-LG" },
      { id: vid(), name: "Charcoal", type: "color", value: "#36454F", priceModifier: 0, stock: 8, sku: "MS-CH" },
      { id: vid(), name: "Navy Blue", type: "color", value: "#000080", priceModifier: 100, stock: 5, sku: "MS-NB" },
      { id: vid(), name: "Olive Green", type: "color", value: "#556B2F", priceModifier: 100, stock: 3, sku: "MS-OG" },
    ],
    specs: [
      { label: "Frame", value: "Kiln-dried hardwood" },
      { label: "Upholstery", value: "Performance polyester blend" },
      { label: "Cushion Fill", value: "High-resilience foam with fiber wrap" },
      { label: "Seat Height", value: '18"' },
      { label: "Leg Finish", value: "Natural oak" },
    ],
    stock: 28,
    rating: 4.6,
    reviewCount: 124,
    weight: 145,
    dimensions: { width: 88, height: 34, depth: 38 },
    sku: "FSOW-MS-001",
    createdAt: "2025-03-15T10:00:00Z",
    updatedAt: "2025-11-20T14:30:00Z",
  },
  {
    id: "prod-002",
    name: "Leather Armchair",
    slug: "leather-armchair",
    description:
      "Timeless wingback armchair upholstered in full-grain Italian leather. Features hand-tied coil springs, solid walnut legs, and generous padding for luxurious comfort. Ages beautifully with a rich patina over time.",
    shortDescription: "Full-grain Italian leather wingback armchair with walnut legs.",
    price: 1499,
    compareAtPrice: null,
    categoryId: "cat-living-room",
    subcategoryId: "sub-armchairs",
    status: "active",
    featured: true,
    tags: ["premium", "handcrafted"],
    images: productGallery("leather-armchair"),
    thumbnail: productThumb("leather-armchair"),
    variants: [
      { id: vid(), name: "Cognac", type: "color", value: "#9A4E1C", priceModifier: 0, stock: 7, sku: "LA-CG" },
      { id: vid(), name: "Black", type: "color", value: "#1A1A1A", priceModifier: 0, stock: 10, sku: "LA-BK" },
      { id: vid(), name: "Dark Brown", type: "color", value: "#3B2314", priceModifier: 0, stock: 4, sku: "LA-DB" },
    ],
    specs: [
      { label: "Leather", value: "Full-grain Italian aniline" },
      { label: "Frame", value: "Solid hardwood" },
      { label: "Springs", value: "Hand-tied 8-way coil" },
      { label: "Legs", value: "Solid walnut" },
      { label: "Seat Height", value: '19"' },
    ],
    stock: 21,
    rating: 4.8,
    reviewCount: 87,
    weight: 68,
    dimensions: { width: 32, height: 42, depth: 34 },
    sku: "FSOW-LA-002",
    createdAt: "2025-02-10T10:00:00Z",
    updatedAt: "2025-10-05T09:15:00Z",
  },
  {
    id: "prod-003",
    name: "Oval Coffee Table",
    slug: "oval-coffee-table",
    description:
      "An organically shaped oval coffee table crafted from solid white oak with a hand-rubbed natural oil finish. The sculptural pedestal base adds visual interest while keeping the floor open. Perfect for modern and Scandinavian interiors.",
    shortDescription: "Solid white oak oval coffee table with sculptural pedestal base.",
    price: 749,
    compareAtPrice: 899,
    categoryId: "cat-living-room",
    subcategoryId: "sub-coffee-tables",
    status: "active",
    featured: false,
    tags: ["sustainable", "handcrafted"],
    images: productGallery("oval-coffee-table"),
    thumbnail: productThumb("oval-coffee-table"),
    variants: [
      { id: vid(), name: "Natural Oak", type: "material", value: "natural-oak", priceModifier: 0, stock: 15, sku: "OCT-NO" },
      { id: vid(), name: "Walnut", type: "material", value: "walnut", priceModifier: 150, stock: 9, sku: "OCT-WN" },
    ],
    specs: [
      { label: "Material", value: "Solid white oak" },
      { label: "Finish", value: "Hand-rubbed natural oil" },
      { label: "Shape", value: "Oval" },
      { label: "Weight Capacity", value: "75 lbs" },
    ],
    stock: 24,
    rating: 4.5,
    reviewCount: 56,
    weight: 55,
    dimensions: { width: 48, height: 16, depth: 28 },
    sku: "FSOW-OCT-003",
    createdAt: "2025-04-20T10:00:00Z",
    updatedAt: "2025-09-12T11:00:00Z",
  },
  {
    id: "prod-004",
    name: "Modular Sectional Sofa",
    slug: "modular-sectional-sofa",
    description:
      "A fully customizable modular sectional that adapts to your space. Each module connects with hidden brackets for a seamless look. Stain-resistant performance velvet, reversible cushions, and an integrated USB charging port in the armrest.",
    shortDescription: "Customizable modular sectional with stain-resistant performance velvet.",
    price: 3499,
    compareAtPrice: 4199,
    categoryId: "cat-living-room",
    subcategoryId: "sub-sofas",
    status: "active",
    featured: true,
    tags: ["bestseller", "modular", "free-shipping"],
    images: productGallery("modular-sectional"),
    thumbnail: productThumb("modular-sectional"),
    variants: [
      { id: vid(), name: "Cream", type: "color", value: "#FFFDD0", priceModifier: 0, stock: 6, sku: "MSS-CR" },
      { id: vid(), name: "Slate", type: "color", value: "#708090", priceModifier: 0, stock: 4, sku: "MSS-SL" },
      { id: vid(), name: "Forest", type: "color", value: "#228B22", priceModifier: 200, stock: 3, sku: "MSS-FR" },
    ],
    specs: [
      { label: "Configuration", value: "5-piece L-shape (configurable)" },
      { label: "Upholstery", value: "Performance velvet" },
      { label: "Frame", value: "Engineered hardwood" },
      { label: "Features", value: "USB charging, hidden brackets" },
    ],
    stock: 13,
    rating: 4.7,
    reviewCount: 203,
    weight: 280,
    dimensions: { width: 120, height: 34, depth: 90 },
    sku: "FSOW-MSS-004",
    createdAt: "2025-01-05T10:00:00Z",
    updatedAt: "2025-12-01T16:45:00Z",
  },
  {
    id: "prod-005",
    name: "Tall Bookshelf",
    slug: "tall-bookshelf",
    description:
      "A statement-making tall bookshelf with an open-back ladder design. Crafted from solid mango wood with black iron frame accents. Five generous shelves provide ample display and storage space.",
    shortDescription: "Solid mango wood ladder bookshelf with iron frame and five shelves.",
    price: 649,
    compareAtPrice: null,
    categoryId: "cat-living-room",
    subcategoryId: "sub-bookshelves",
    status: "active",
    featured: false,
    tags: ["industrial", "sustainable"],
    images: productGallery("tall-bookshelf"),
    thumbnail: productThumb("tall-bookshelf"),
    variants: [
      { id: vid(), name: "Natural/Black", type: "material", value: "natural-black", priceModifier: 0, stock: 18, sku: "TB-NB" },
      { id: vid(), name: "Dark Walnut/Brass", type: "material", value: "walnut-brass", priceModifier: 100, stock: 7, sku: "TB-WB" },
    ],
    specs: [
      { label: "Shelves", value: "5 fixed shelves" },
      { label: "Material", value: "Solid mango wood, powder-coated iron" },
      { label: "Weight Capacity", value: "25 lbs per shelf" },
      { label: "Wall Anchor", value: "Included" },
    ],
    stock: 25,
    rating: 4.4,
    reviewCount: 42,
    weight: 72,
    dimensions: { width: 36, height: 78, depth: 14 },
    sku: "FSOW-TB-005",
    createdAt: "2025-05-10T10:00:00Z",
    updatedAt: "2025-08-20T10:00:00Z",
  },
  {
    id: "prod-006",
    name: "Velvet Accent Chair",
    slug: "velvet-accent-chair",
    description:
      "A plush velvet accent chair with channel tufting and tapered brass legs. The barrel-back silhouette adds a touch of mid-century glamour to any living room or reading nook.",
    shortDescription: "Channel-tufted velvet accent chair with brass legs.",
    price: 699,
    compareAtPrice: 849,
    categoryId: "cat-living-room",
    subcategoryId: "sub-armchairs",
    status: "active",
    featured: false,
    tags: ["mid-century", "velvet"],
    images: productGallery("velvet-accent-chair"),
    thumbnail: productThumb("velvet-accent-chair"),
    variants: [
      { id: vid(), name: "Emerald", type: "color", value: "#50C878", priceModifier: 0, stock: 11, sku: "VAC-EM" },
      { id: vid(), name: "Blush", type: "color", value: "#DE5D83", priceModifier: 0, stock: 9, sku: "VAC-BL" },
      { id: vid(), name: "Mustard", type: "color", value: "#FFDB58", priceModifier: 0, stock: 6, sku: "VAC-MU" },
      { id: vid(), name: "Navy", type: "color", value: "#000080", priceModifier: 0, stock: 14, sku: "VAC-NV" },
    ],
    specs: [
      { label: "Upholstery", value: "Velvet polyester" },
      { label: "Legs", value: "Tapered brass-finished steel" },
      { label: "Seat Height", value: '17.5"' },
      { label: "Max Weight", value: "300 lbs" },
    ],
    stock: 40,
    rating: 4.3,
    reviewCount: 68,
    weight: 38,
    dimensions: { width: 30, height: 32, depth: 29 },
    sku: "FSOW-VAC-006",
    createdAt: "2025-06-01T10:00:00Z",
    updatedAt: "2025-10-15T12:00:00Z",
  },
  {
    id: "prod-007",
    name: "Glass Coffee Table",
    slug: "glass-coffee-table",
    description:
      "A minimalist coffee table featuring a tempered glass top on a geometric brushed-brass base. The transparent surface keeps the room feeling open and airy while the metal base adds a modern sculptural element.",
    shortDescription: "Tempered glass top coffee table with geometric brass base.",
    price: 549,
    compareAtPrice: null,
    categoryId: "cat-living-room",
    subcategoryId: "sub-coffee-tables",
    status: "active",
    featured: false,
    tags: ["modern", "minimalist"],
    images: productGallery("glass-coffee-table"),
    thumbnail: productThumb("glass-coffee-table"),
    variants: [
      { id: vid(), name: "Brass", type: "material", value: "brass", priceModifier: 0, stock: 20, sku: "GCT-BR" },
      { id: vid(), name: "Chrome", type: "material", value: "chrome", priceModifier: 0, stock: 15, sku: "GCT-CR" },
    ],
    specs: [
      { label: "Top", value: '10mm tempered glass, 0.39" thick' },
      { label: "Base", value: "Stainless steel, brushed finish" },
      { label: "Shape", value: "Round, 36\" diameter" },
      { label: "Weight Capacity", value: "50 lbs" },
    ],
    stock: 35,
    rating: 4.2,
    reviewCount: 34,
    weight: 42,
    dimensions: { width: 36, height: 17, depth: 36 },
    sku: "FSOW-GCT-007",
    createdAt: "2025-07-15T10:00:00Z",
    updatedAt: "2025-11-01T09:00:00Z",
  },
  {
    id: "prod-008",
    name: "Mid-Century TV Stand",
    slug: "mid-century-tv-stand",
    description:
      "A mid-century modern media console in solid acacia wood with sliding doors and cable management. The warm honey finish and splayed legs evoke retro charm while accommodating modern electronics up to 65 inches.",
    shortDescription: "Solid acacia wood media console with sliding doors, fits up to 65\" TVs.",
    price: 899,
    compareAtPrice: 1099,
    categoryId: "cat-living-room",
    subcategoryId: "sub-tv-stands",
    status: "active",
    featured: false,
    tags: ["mid-century", "storage"],
    images: productGallery("mid-century-tv-stand"),
    thumbnail: productThumb("mid-century-tv-stand"),
    variants: [
      { id: vid(), name: "Honey Acacia", type: "material", value: "honey-acacia", priceModifier: 0, stock: 11, sku: "MCTS-HA" },
      { id: vid(), name: "Espresso", type: "material", value: "espresso", priceModifier: 0, stock: 8, sku: "MCTS-ES" },
    ],
    specs: [
      { label: "Material", value: "Solid acacia wood" },
      { label: "TV Size", value: "Up to 65\"" },
      { label: "Storage", value: "2 sliding doors, 2 open shelves" },
      { label: "Cable Management", value: "Built-in cutouts" },
    ],
    stock: 19,
    rating: 4.5,
    reviewCount: 51,
    weight: 88,
    dimensions: { width: 60, height: 24, depth: 16 },
    sku: "FSOW-MCTS-008",
    createdAt: "2025-03-01T10:00:00Z",
    updatedAt: "2025-09-28T14:00:00Z",
  },
  {
    id: "prod-009",
    name: "Sleeper Sofa",
    slug: "sleeper-sofa",
    description:
      "A versatile queen sleeper sofa that seamlessly transitions from stylish seating to comfortable bed. Features a premium innerspring mattress, track arms, and durable linen-blend upholstery. Ideal for studio apartments and guest rooms.",
    shortDescription: "Queen sleeper sofa with innerspring mattress and linen-blend fabric.",
    price: 2199,
    compareAtPrice: 2699,
    categoryId: "cat-living-room",
    subcategoryId: "sub-sofas",
    status: "active",
    featured: false,
    tags: ["multifunctional", "guest-room"],
    images: productGallery("sleeper-sofa"),
    thumbnail: productThumb("sleeper-sofa"),
    variants: [
      { id: vid(), name: "Oatmeal", type: "color", value: "#C8B896", priceModifier: 0, stock: 5, sku: "SS-OT" },
      { id: vid(), name: "Steel Blue", type: "color", value: "#4682B4", priceModifier: 0, stock: 4, sku: "SS-SB" },
    ],
    specs: [
      { label: "Mattress", value: "Queen innerspring, 4.5\" thick" },
      { label: "Mechanism", value: "Pull-out sleeper" },
      { label: "Upholstery", value: "Linen-polyester blend" },
      { label: "Sleeps", value: "2 adults" },
    ],
    stock: 9,
    rating: 4.1,
    reviewCount: 39,
    weight: 190,
    dimensions: { width: 82, height: 35, depth: 37 },
    sku: "FSOW-SS-009",
    createdAt: "2025-04-05T10:00:00Z",
    updatedAt: "2025-11-10T11:30:00Z",
  },
  {
    id: "prod-010",
    name: "Floating TV Console",
    slug: "floating-tv-console",
    description:
      "A wall-mounted floating media console in matte white lacquer with walnut accent panels. Gives a clean, modern look while freeing up floor space. Includes mounting hardware and supports TVs up to 70 inches.",
    shortDescription: "Wall-mounted floating media console in matte lacquer with walnut accents.",
    price: 799,
    compareAtPrice: null,
    categoryId: "cat-living-room",
    subcategoryId: "sub-tv-stands",
    status: "active",
    featured: false,
    tags: ["modern", "space-saving"],
    images: productGallery("floating-tv-console"),
    thumbnail: productThumb("floating-tv-console"),
    variants: [
      { id: vid(), name: "White/Walnut", type: "material", value: "white-walnut", priceModifier: 0, stock: 14, sku: "FTC-WW" },
      { id: vid(), name: "Black/Oak", type: "material", value: "black-oak", priceModifier: 0, stock: 10, sku: "FTC-BO" },
    ],
    specs: [
      { label: "Material", value: "MDF with lacquer finish, solid walnut veneer" },
      { label: "TV Size", value: "Up to 70\"" },
      { label: "Mounting", value: "Wall-mounted, hardware included" },
      { label: "Weight Capacity", value: "100 lbs" },
    ],
    stock: 24,
    rating: 4.6,
    reviewCount: 29,
    weight: 65,
    dimensions: { width: 72, height: 14, depth: 15 },
    sku: "FSOW-FTC-010",
    createdAt: "2025-08-01T10:00:00Z",
    updatedAt: "2025-12-05T08:00:00Z",
  },
  {
    id: "prod-011",
    name: "Wall Bookshelf Unit",
    slug: "wall-bookshelf-unit",
    description:
      "A modular wall-mounted bookshelf system that lets you create a custom library wall. Solid ash wood shelves on a matte black steel grid. Each unit includes 6 shelves and can be combined for wider installations.",
    shortDescription: "Modular wall-mounted ash wood bookshelf on steel grid system.",
    price: 549,
    compareAtPrice: null,
    categoryId: "cat-living-room",
    subcategoryId: "sub-bookshelves",
    status: "draft",
    featured: false,
    tags: ["modular", "wall-mounted"],
    images: productGallery("wall-bookshelf-unit"),
    thumbnail: productThumb("wall-bookshelf-unit"),
    variants: [
      { id: vid(), name: "Ash/Black", type: "material", value: "ash-black", priceModifier: 0, stock: 22, sku: "WBU-AB" },
    ],
    specs: [
      { label: "Material", value: "Solid ash wood, powder-coated steel" },
      { label: "Shelves", value: "6 adjustable" },
      { label: "Weight Capacity", value: "20 lbs per shelf" },
      { label: "Mounting", value: "Wall-mounted, hardware included" },
    ],
    stock: 22,
    rating: 0,
    reviewCount: 0,
    weight: 45,
    dimensions: { width: 40, height: 72, depth: 10 },
    sku: "FSOW-WBU-011",
    createdAt: "2025-11-20T10:00:00Z",
    updatedAt: "2025-11-20T10:00:00Z",
  },
  {
    id: "prod-012",
    name: "Linen Loveseat",
    slug: "linen-loveseat",
    description:
      "A compact loveseat wrapped in washed Belgian linen with a relaxed slipcover feel. Ideal for small living rooms, reading nooks, or bedrooms. Features a kiln-dried hardwood frame and down-blend cushions.",
    shortDescription: "Washed Belgian linen loveseat with relaxed slipcover and down-blend cushions.",
    price: 1299,
    compareAtPrice: null,
    categoryId: "cat-living-room",
    subcategoryId: "sub-sofas",
    status: "active",
    featured: false,
    tags: ["linen", "small-space"],
    images: productGallery("linen-loveseat"),
    thumbnail: productThumb("linen-loveseat"),
    variants: [
      { id: vid(), name: "White", type: "color", value: "#F5F5F5", priceModifier: 0, stock: 7, sku: "LL-WH" },
      { id: vid(), name: "Sand", type: "color", value: "#C2B280", priceModifier: 0, stock: 10, sku: "LL-SD" },
      { id: vid(), name: "Denim Blue", type: "color", value: "#1560BD", priceModifier: 50, stock: 5, sku: "LL-DB" },
    ],
    specs: [
      { label: "Upholstery", value: "100% Belgian linen, pre-washed" },
      { label: "Cushion Fill", value: "Down-blend wrapped foam" },
      { label: "Seat Width", value: '52"' },
      { label: "Cover", value: "Removable, machine-washable" },
    ],
    stock: 22,
    rating: 4.7,
    reviewCount: 15,
    weight: 95,
    dimensions: { width: 64, height: 33, depth: 36 },
    sku: "FSOW-LL-012",
    createdAt: "2025-09-10T10:00:00Z",
    updatedAt: "2025-12-01T10:00:00Z",
  },
  // ===== BEDROOM =====
  {
    id: "prod-013",
    name: "Upholstered Bed Frame",
    slug: "upholstered-bed-frame",
    description:
      "A luxuriously padded upholstered bed frame with a tall wingback headboard. The platform design eliminates the need for a box spring. Available in Queen and King sizes. Covered in durable boucle fabric.",
    shortDescription: "Boucle-upholstered platform bed with wingback headboard.",
    price: 1599,
    compareAtPrice: 1999,
    categoryId: "cat-bedroom",
    subcategoryId: "sub-beds",
    status: "active",
    featured: true,
    tags: ["bestseller", "free-shipping"],
    images: productGallery("upholstered-bed-frame"),
    thumbnail: productThumb("upholstered-bed-frame"),
    variants: [
      { id: vid(), name: "Queen - Cream", type: "size", value: "queen-cream", priceModifier: 0, stock: 10, sku: "UBF-QC" },
      { id: vid(), name: "Queen - Gray", type: "size", value: "queen-gray", priceModifier: 0, stock: 8, sku: "UBF-QG" },
      { id: vid(), name: "King - Cream", type: "size", value: "king-cream", priceModifier: 300, stock: 6, sku: "UBF-KC" },
      { id: vid(), name: "King - Gray", type: "size", value: "king-gray", priceModifier: 300, stock: 4, sku: "UBF-KG" },
    ],
    specs: [
      { label: "Upholstery", value: "Boucle polyester" },
      { label: "Platform", value: "Slat system, no box spring needed" },
      { label: "Headboard Height", value: '52"' },
      { label: "Clearance", value: '7" under-bed clearance' },
    ],
    stock: 28,
    rating: 4.6,
    reviewCount: 156,
    weight: 125,
    dimensions: { width: 65, height: 52, depth: 87 },
    sku: "FSOW-UBF-013",
    createdAt: "2025-01-20T10:00:00Z",
    updatedAt: "2025-11-30T15:00:00Z",
  },
  {
    id: "prod-014",
    name: "Walnut Nightstand",
    slug: "walnut-nightstand",
    description:
      "A mid-century inspired nightstand in solid American walnut. Features one drawer with soft-close hardware and an open lower shelf. The tapered legs and beveled edges give it a timeless sophistication.",
    shortDescription: "Solid American walnut nightstand with soft-close drawer.",
    price: 449,
    compareAtPrice: null,
    categoryId: "cat-bedroom",
    subcategoryId: "sub-nightstands",
    status: "active",
    featured: false,
    tags: ["mid-century", "handcrafted"],
    images: productGallery("walnut-nightstand"),
    thumbnail: productThumb("walnut-nightstand"),
    variants: [
      { id: vid(), name: "Natural Walnut", type: "material", value: "natural-walnut", priceModifier: 0, stock: 25, sku: "WN-NW" },
      { id: vid(), name: "Walnut/White Drawer", type: "material", value: "walnut-white", priceModifier: 50, stock: 12, sku: "WN-WW" },
    ],
    specs: [
      { label: "Material", value: "Solid American walnut" },
      { label: "Drawer", value: "1 with soft-close slides" },
      { label: "Shelf", value: "1 open lower shelf" },
      { label: "Finish", value: "Natural lacquer" },
    ],
    stock: 37,
    rating: 4.7,
    reviewCount: 93,
    weight: 32,
    dimensions: { width: 22, height: 24, depth: 18 },
    sku: "FSOW-WN-014",
    createdAt: "2025-02-15T10:00:00Z",
    updatedAt: "2025-10-10T09:00:00Z",
  },
  {
    id: "prod-015",
    name: "6-Drawer Dresser",
    slug: "6-drawer-dresser",
    description:
      "A spacious 6-drawer dresser in white oak with rounded edges and a clean Scandinavian aesthetic. Full-extension drawers with soft-close glides ensure smooth operation. The solid oak top can double as a vanity surface.",
    shortDescription: "White oak 6-drawer dresser with Scandinavian design and soft-close drawers.",
    price: 1299,
    compareAtPrice: 1499,
    categoryId: "cat-bedroom",
    subcategoryId: "sub-dressers",
    status: "active",
    featured: false,
    tags: ["scandinavian", "storage"],
    images: productGallery("6-drawer-dresser"),
    thumbnail: productThumb("6-drawer-dresser"),
    variants: [
      { id: vid(), name: "White Oak", type: "material", value: "white-oak", priceModifier: 0, stock: 9, sku: "6DD-WO" },
      { id: vid(), name: "Smoke Oak", type: "material", value: "smoke-oak", priceModifier: 100, stock: 5, sku: "6DD-SO" },
    ],
    specs: [
      { label: "Material", value: "Solid white oak" },
      { label: "Drawers", value: "6, full-extension, soft-close" },
      { label: "Interior Depth", value: '5"' },
      { label: "Anti-Tip", value: "Wall anchor hardware included" },
    ],
    stock: 14,
    rating: 4.4,
    reviewCount: 47,
    weight: 140,
    dimensions: { width: 60, height: 34, depth: 20 },
    sku: "FSOW-6DD-015",
    createdAt: "2025-03-25T10:00:00Z",
    updatedAt: "2025-10-20T12:00:00Z",
  },
  {
    id: "prod-016",
    name: "Platform Bed Frame",
    slug: "platform-bed-frame",
    description:
      "A minimalist solid wood platform bed with a floating design and integrated headboard. Japanese-inspired joinery eliminates visible hardware. The low-profile silhouette creates a serene, grounded bedroom aesthetic.",
    shortDescription: "Japanese-inspired solid wood platform bed with floating design.",
    price: 1199,
    compareAtPrice: null,
    categoryId: "cat-bedroom",
    subcategoryId: "sub-beds",
    status: "active",
    featured: false,
    tags: ["japanese", "minimalist"],
    images: productGallery("platform-bed-frame"),
    thumbnail: productThumb("platform-bed-frame"),
    variants: [
      { id: vid(), name: "Queen - Natural Ash", type: "size", value: "queen-ash", priceModifier: 0, stock: 7, sku: "PBF-QA" },
      { id: vid(), name: "King - Natural Ash", type: "size", value: "king-ash", priceModifier: 250, stock: 5, sku: "PBF-KA" },
      { id: vid(), name: "Queen - Ebony", type: "size", value: "queen-ebony", priceModifier: 100, stock: 4, sku: "PBF-QE" },
      { id: vid(), name: "King - Ebony", type: "size", value: "king-ebony", priceModifier: 350, stock: 3, sku: "PBF-KE" },
    ],
    specs: [
      { label: "Material", value: "Solid North American ash" },
      { label: "Joinery", value: "Mortise and tenon, no visible hardware" },
      { label: "Profile", value: '8" total height' },
      { label: "Slat System", value: "Included, no box spring needed" },
    ],
    stock: 19,
    rating: 4.8,
    reviewCount: 31,
    weight: 110,
    dimensions: { width: 64, height: 8, depth: 86 },
    sku: "FSOW-PBF-016",
    createdAt: "2025-05-05T10:00:00Z",
    updatedAt: "2025-11-15T10:00:00Z",
  },
  {
    id: "prod-017",
    name: "Modern Wardrobe",
    slug: "modern-wardrobe",
    description:
      "A freestanding wardrobe with sliding doors in a matte lacquer finish. Interior includes a full-length hanging rod, adjustable shelves, and a built-in drawer. Mirrored interior door panel adds functionality.",
    shortDescription: "Sliding-door wardrobe with matte lacquer finish and mirrored interior.",
    price: 2199,
    compareAtPrice: 2599,
    categoryId: "cat-bedroom",
    subcategoryId: "sub-wardrobes",
    status: "active",
    featured: false,
    tags: ["storage", "modern"],
    images: productGallery("modern-wardrobe"),
    thumbnail: productThumb("modern-wardrobe"),
    variants: [
      { id: vid(), name: "Matte White", type: "color", value: "#FFFFFF", priceModifier: 0, stock: 6, sku: "MW-MW" },
      { id: vid(), name: "Matte Black", type: "color", value: "#1A1A1A", priceModifier: 0, stock: 4, sku: "MW-MB" },
    ],
    specs: [
      { label: "Material", value: "Engineered wood with lacquer finish" },
      { label: "Doors", value: "2 sliding, soft-close" },
      { label: "Interior", value: "Hanging rod, 4 shelves, 1 drawer" },
      { label: "Mirror", value: "Full-length on interior door" },
    ],
    stock: 10,
    rating: 4.3,
    reviewCount: 22,
    weight: 195,
    dimensions: { width: 60, height: 80, depth: 24 },
    sku: "FSOW-MW-017",
    createdAt: "2025-06-15T10:00:00Z",
    updatedAt: "2025-10-30T14:00:00Z",
  },
  {
    id: "prod-018",
    name: "Marble-Top Nightstand",
    slug: "marble-top-nightstand",
    description:
      "A luxurious nightstand featuring a genuine Carrara marble top on a brass-finished steel frame. The single drawer with a velvet-lined interior keeps small items organized. A true statement piece for the modern bedroom.",
    shortDescription: "Carrara marble top nightstand with brass frame and velvet-lined drawer.",
    price: 599,
    compareAtPrice: null,
    categoryId: "cat-bedroom",
    subcategoryId: "sub-nightstands",
    status: "active",
    featured: false,
    tags: ["luxury", "marble"],
    images: productGallery("marble-nightstand"),
    thumbnail: productThumb("marble-nightstand"),
    variants: [
      { id: vid(), name: "White Marble/Brass", type: "material", value: "marble-brass", priceModifier: 0, stock: 8, sku: "MN-MB" },
      { id: vid(), name: "Black Marble/Chrome", type: "material", value: "marble-chrome", priceModifier: 50, stock: 5, sku: "MN-MC" },
    ],
    specs: [
      { label: "Top", value: "Genuine Carrara marble" },
      { label: "Frame", value: "Steel with brass or chrome finish" },
      { label: "Drawer", value: "1, velvet-lined" },
      { label: "Care", value: "Seal marble annually" },
    ],
    stock: 13,
    rating: 4.5,
    reviewCount: 18,
    weight: 45,
    dimensions: { width: 20, height: 22, depth: 16 },
    sku: "FSOW-MN-018",
    createdAt: "2025-07-20T10:00:00Z",
    updatedAt: "2025-11-05T09:00:00Z",
  },
  {
    id: "prod-019",
    name: "Compact Dresser",
    slug: "compact-dresser",
    description:
      "A space-conscious 3-drawer dresser perfect for smaller bedrooms and apartments. Built from solid pine with a warm honey finish. Rounded corners and leather-wrapped pulls add a modern organic touch.",
    shortDescription: "Space-saving 3-drawer pine dresser with leather-wrapped pulls.",
    price: 599,
    compareAtPrice: 699,
    categoryId: "cat-bedroom",
    subcategoryId: "sub-dressers",
    status: "active",
    featured: false,
    tags: ["small-space", "organic"],
    images: productGallery("compact-dresser"),
    thumbnail: productThumb("compact-dresser"),
    variants: [
      { id: vid(), name: "Honey Pine", type: "material", value: "honey-pine", priceModifier: 0, stock: 16, sku: "CD-HP" },
      { id: vid(), name: "White Pine", type: "material", value: "white-pine", priceModifier: 0, stock: 12, sku: "CD-WP" },
    ],
    specs: [
      { label: "Material", value: "Solid pine" },
      { label: "Drawers", value: "3, soft-close" },
      { label: "Pulls", value: "Leather-wrapped brass" },
      { label: "Finish", value: "Water-based lacquer" },
    ],
    stock: 28,
    rating: 4.2,
    reviewCount: 33,
    weight: 65,
    dimensions: { width: 36, height: 32, depth: 18 },
    sku: "FSOW-CD-019",
    createdAt: "2025-08-10T10:00:00Z",
    updatedAt: "2025-11-25T11:00:00Z",
  },
  {
    id: "prod-020",
    name: "Canopy Bed Frame",
    slug: "canopy-bed-frame",
    description:
      "A dramatic canopy bed with a slim black iron frame that adds architectural interest without overwhelming the room. The simple four-post design pairs beautifully with draped linens or left bare for a minimalist look.",
    shortDescription: "Slim black iron canopy bed frame with architectural four-post design.",
    price: 999,
    compareAtPrice: null,
    categoryId: "cat-bedroom",
    subcategoryId: "sub-beds",
    status: "active",
    featured: false,
    tags: ["statement", "iron"],
    images: productGallery("canopy-bed-frame"),
    thumbnail: productThumb("canopy-bed-frame"),
    variants: [
      { id: vid(), name: "Queen - Matte Black", type: "size", value: "queen-black", priceModifier: 0, stock: 9, sku: "CBF-QB" },
      { id: vid(), name: "King - Matte Black", type: "size", value: "king-black", priceModifier: 200, stock: 5, sku: "CBF-KB" },
      { id: vid(), name: "Queen - Brass", type: "size", value: "queen-brass", priceModifier: 200, stock: 3, sku: "CBF-QBR" },
    ],
    specs: [
      { label: "Material", value: "Powder-coated steel" },
      { label: "Canopy Height", value: '78"' },
      { label: "Frame Profile", value: '1.5" tube' },
      { label: "Slat System", value: "Metal slats included" },
    ],
    stock: 17,
    rating: 4.4,
    reviewCount: 26,
    weight: 85,
    dimensions: { width: 63, height: 78, depth: 84 },
    sku: "FSOW-CBF-020",
    createdAt: "2025-04-15T10:00:00Z",
    updatedAt: "2025-09-20T10:00:00Z",
  },
  {
    id: "prod-021",
    name: "Sliding Door Wardrobe",
    slug: "sliding-door-wardrobe",
    description:
      "A contemporary wardrobe with oak-veneer sliding doors and interior LED lighting that activates when doors open. Full-width hanging bar, pull-out trouser rack, and adjustable shelving. Assembly service available.",
    shortDescription: "Oak-veneer wardrobe with LED lighting and pull-out trouser rack.",
    price: 1899,
    compareAtPrice: null,
    categoryId: "cat-bedroom",
    subcategoryId: "sub-wardrobes",
    status: "draft",
    featured: false,
    tags: ["smart-storage", "led"],
    images: productGallery("sliding-wardrobe"),
    thumbnail: productThumb("sliding-wardrobe"),
    variants: [
      { id: vid(), name: "Light Oak", type: "material", value: "light-oak", priceModifier: 0, stock: 3, sku: "SDW-LO" },
    ],
    specs: [
      { label: "Material", value: "Engineered wood with oak veneer" },
      { label: "Doors", value: "2 sliding, soft-close track" },
      { label: "Interior", value: "Hanging bar, trouser rack, 5 shelves" },
      { label: "Lighting", value: "LED strip, motion-activated" },
    ],
    stock: 3,
    rating: 0,
    reviewCount: 0,
    weight: 210,
    dimensions: { width: 72, height: 84, depth: 26 },
    sku: "FSOW-SDW-021",
    createdAt: "2025-12-01T10:00:00Z",
    updatedAt: "2025-12-01T10:00:00Z",
  },
  {
    id: "prod-022",
    name: "Hybrid Mattress",
    slug: "hybrid-mattress",
    description:
      "A medium-firm hybrid mattress combining individually wrapped coils with a 3-inch layer of gel-infused memory foam. CertiPUR-US certified foam, breathable quilted cover, and reinforced edge support for full-surface sleeping.",
    shortDescription: "Medium-firm hybrid mattress with gel memory foam and wrapped coils.",
    price: 999,
    compareAtPrice: 1299,
    categoryId: "cat-bedroom",
    subcategoryId: "sub-mattresses",
    status: "active",
    featured: false,
    tags: ["bestseller", "free-shipping"],
    images: productGallery("hybrid-mattress"),
    thumbnail: productThumb("hybrid-mattress"),
    variants: [
      { id: vid(), name: "Twin", type: "size", value: "twin", priceModifier: -300, stock: 15, sku: "HM-TW" },
      { id: vid(), name: "Full", type: "size", value: "full", priceModifier: -150, stock: 12, sku: "HM-FU" },
      { id: vid(), name: "Queen", type: "size", value: "queen", priceModifier: 0, stock: 20, sku: "HM-QU" },
      { id: vid(), name: "King", type: "size", value: "king", priceModifier: 200, stock: 10, sku: "HM-KI" },
    ],
    specs: [
      { label: "Construction", value: "Hybrid (coil + foam)" },
      { label: "Firmness", value: "Medium-firm (6.5/10)" },
      { label: "Thickness", value: '12"' },
      { label: "Certification", value: "CertiPUR-US" },
      { label: "Trial", value: "100-night risk-free trial" },
    ],
    stock: 57,
    rating: 4.5,
    reviewCount: 312,
    weight: 85,
    dimensions: { width: 60, height: 12, depth: 80 },
    sku: "FSOW-HM-022",
    createdAt: "2025-01-10T10:00:00Z",
    updatedAt: "2025-12-10T10:00:00Z",
  },
  // ===== DINING =====
  {
    id: "prod-023",
    name: "Extendable Dining Table",
    slug: "extendable-dining-table",
    description:
      "A solid oak dining table with a butterfly leaf extension that expands from 60 to 84 inches. Comfortably seats 6 to 10 guests. The clean rectangular top and tapered legs make it versatile for both casual and formal dining.",
    shortDescription: "Solid oak extendable dining table, seats 6-10 with butterfly leaf.",
    price: 1799,
    compareAtPrice: 2199,
    categoryId: "cat-dining",
    subcategoryId: "sub-dining-tables",
    status: "active",
    featured: true,
    tags: ["bestseller", "extendable", "free-shipping"],
    images: productGallery("extendable-dining-table"),
    thumbnail: productThumb("extendable-dining-table"),
    variants: [
      { id: vid(), name: "Natural Oak", type: "material", value: "natural-oak", priceModifier: 0, stock: 8, sku: "EDT-NO" },
      { id: vid(), name: "Dark Oak", type: "material", value: "dark-oak", priceModifier: 0, stock: 6, sku: "EDT-DO" },
    ],
    specs: [
      { label: "Material", value: "Solid European oak" },
      { label: "Length", value: "60\" (84\" extended)" },
      { label: "Seating", value: "6 standard, 10 extended" },
      { label: "Extension", value: "Self-storing butterfly leaf" },
    ],
    stock: 14,
    rating: 4.7,
    reviewCount: 89,
    weight: 155,
    dimensions: { width: 60, height: 30, depth: 36 },
    sku: "FSOW-EDT-023",
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2025-11-20T10:00:00Z",
  },
  {
    id: "prod-024",
    name: "Upholstered Dining Chair",
    slug: "upholstered-dining-chair",
    description:
      "An elegant dining chair with a curved backrest and padded seat upholstered in performance linen. Solid beech wood legs with a natural finish. Sold individually or as a set of 2. Stain-resistant fabric makes it family-friendly.",
    shortDescription: "Performance linen dining chair with curved back and beech wood legs.",
    price: 299,
    compareAtPrice: null,
    categoryId: "cat-dining",
    subcategoryId: "sub-dining-chairs",
    status: "active",
    featured: false,
    tags: ["family-friendly", "set-available"],
    images: productGallery("upholstered-dining-chair"),
    thumbnail: productThumb("upholstered-dining-chair"),
    variants: [
      { id: vid(), name: "Linen White", type: "color", value: "#FAF0E6", priceModifier: 0, stock: 30, sku: "UDC-LW" },
      { id: vid(), name: "Sage Green", type: "color", value: "#B2AC88", priceModifier: 0, stock: 18, sku: "UDC-SG" },
      { id: vid(), name: "Charcoal", type: "color", value: "#36454F", priceModifier: 0, stock: 22, sku: "UDC-CH" },
    ],
    specs: [
      { label: "Seat Material", value: "Performance linen blend" },
      { label: "Frame", value: "Solid beech wood" },
      { label: "Seat Height", value: '18.5"' },
      { label: "Max Weight", value: "350 lbs" },
    ],
    stock: 70,
    rating: 4.4,
    reviewCount: 67,
    weight: 18,
    dimensions: { width: 20, height: 34, depth: 22 },
    sku: "FSOW-UDC-024",
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2025-10-05T10:00:00Z",
  },
  {
    id: "prod-025",
    name: "Round Dining Table",
    slug: "round-dining-table",
    description:
      "A stunning round dining table with a solid marble top on a sculptural concrete pedestal base. The 48-inch diameter comfortably seats 4. The pedestal design maximizes legroom and allows flexible chair placement.",
    shortDescription: "Marble top round dining table with concrete pedestal base, seats 4.",
    price: 2499,
    compareAtPrice: null,
    categoryId: "cat-dining",
    subcategoryId: "sub-dining-tables",
    status: "active",
    featured: true,
    tags: ["luxury", "statement"],
    images: productGallery("round-dining-table"),
    thumbnail: productThumb("round-dining-table"),
    variants: [
      { id: vid(), name: "White Marble/Gray Concrete", type: "material", value: "white-gray", priceModifier: 0, stock: 4, sku: "RDT-WG" },
      { id: vid(), name: "Black Marble/Black Concrete", type: "material", value: "black-black", priceModifier: 200, stock: 3, sku: "RDT-BB" },
    ],
    specs: [
      { label: "Top", value: "Honed Carrara marble, 1\" thick" },
      { label: "Base", value: "Fiber-reinforced concrete" },
      { label: "Diameter", value: '48"' },
      { label: "Seating", value: "4 comfortably" },
    ],
    stock: 7,
    rating: 4.9,
    reviewCount: 14,
    weight: 180,
    dimensions: { width: 48, height: 30, depth: 48 },
    sku: "FSOW-RDT-025",
    createdAt: "2025-05-20T10:00:00Z",
    updatedAt: "2025-11-28T09:00:00Z",
  },
  {
    id: "prod-026",
    name: "Counter Height Bar Stool",
    slug: "counter-height-bar-stool",
    description:
      "A sleek counter-height bar stool with a molded plywood seat and chrome hairpin legs. The contoured seat provides surprising comfort without upholstery. Available in a range of wood finishes. Sold individually.",
    shortDescription: "Molded plywood counter stool with chrome hairpin legs, 26\" seat height.",
    price: 199,
    compareAtPrice: 249,
    categoryId: "cat-dining",
    subcategoryId: "sub-bar-stools",
    status: "active",
    featured: false,
    tags: ["modern", "counter-height"],
    images: productGallery("counter-bar-stool"),
    thumbnail: productThumb("counter-bar-stool"),
    variants: [
      { id: vid(), name: "Natural Birch", type: "material", value: "natural-birch", priceModifier: 0, stock: 35, sku: "CBS-NB" },
      { id: vid(), name: "Walnut", type: "material", value: "walnut", priceModifier: 30, stock: 20, sku: "CBS-WN" },
      { id: vid(), name: "White", type: "material", value: "white", priceModifier: 0, stock: 25, sku: "CBS-WH" },
      { id: vid(), name: "Black", type: "material", value: "black", priceModifier: 0, stock: 18, sku: "CBS-BK" },
    ],
    specs: [
      { label: "Seat", value: "Molded plywood" },
      { label: "Legs", value: "Chrome hairpin" },
      { label: "Seat Height", value: '26"' },
      { label: "Footrest", value: "Built-in" },
    ],
    stock: 98,
    rating: 4.3,
    reviewCount: 145,
    weight: 12,
    dimensions: { width: 17, height: 36, depth: 16 },
    sku: "FSOW-CBS-026",
    createdAt: "2025-03-10T10:00:00Z",
    updatedAt: "2025-10-15T11:00:00Z",
  },
  {
    id: "prod-027",
    name: "Farmhouse Dining Table",
    slug: "farmhouse-dining-table",
    description:
      "A rustic farmhouse dining table crafted from reclaimed pine with a naturally distressed finish. The thick turned legs and breadboard ends give it authentic character. Comfortably seats 8. Each table is unique due to the reclaimed wood.",
    shortDescription: "Reclaimed pine farmhouse dining table with turned legs, seats 8.",
    price: 1499,
    compareAtPrice: null,
    categoryId: "cat-dining",
    subcategoryId: "sub-dining-tables",
    status: "active",
    featured: false,
    tags: ["rustic", "sustainable", "reclaimed"],
    images: productGallery("farmhouse-dining-table"),
    thumbnail: productThumb("farmhouse-dining-table"),
    variants: [
      { id: vid(), name: "Natural Reclaimed", type: "material", value: "natural-reclaimed", priceModifier: 0, stock: 5, sku: "FDT-NR" },
      { id: vid(), name: "Whitewash", type: "material", value: "whitewash", priceModifier: 100, stock: 3, sku: "FDT-WW" },
    ],
    specs: [
      { label: "Material", value: "Reclaimed North American pine" },
      { label: "Finish", value: "Water-based polyurethane" },
      { label: "Seating", value: "8 comfortably" },
      { label: "Character", value: "Natural knots and grain variations" },
    ],
    stock: 8,
    rating: 4.6,
    reviewCount: 52,
    weight: 165,
    dimensions: { width: 84, height: 30, depth: 40 },
    sku: "FSOW-FDT-027",
    createdAt: "2025-04-01T10:00:00Z",
    updatedAt: "2025-09-15T10:00:00Z",
  },
  {
    id: "prod-028",
    name: "Windsor Dining Chair",
    slug: "windsor-dining-chair",
    description:
      "A modern take on the classic Windsor chair, handcrafted from solid ash with steam-bent spindles. The sculpted saddle seat provides ergonomic comfort. A timeless design that works in traditional and contemporary settings.",
    shortDescription: "Modern Windsor chair in solid ash with sculpted saddle seat.",
    price: 349,
    compareAtPrice: null,
    categoryId: "cat-dining",
    subcategoryId: "sub-dining-chairs",
    status: "active",
    featured: false,
    tags: ["classic", "handcrafted"],
    images: productGallery("windsor-dining-chair"),
    thumbnail: productThumb("windsor-dining-chair"),
    variants: [
      { id: vid(), name: "Natural Ash", type: "material", value: "natural-ash", priceModifier: 0, stock: 24, sku: "WDC-NA" },
      { id: vid(), name: "Black", type: "color", value: "#1A1A1A", priceModifier: 0, stock: 16, sku: "WDC-BK" },
    ],
    specs: [
      { label: "Material", value: "Solid North American ash" },
      { label: "Construction", value: "Steam-bent spindles" },
      { label: "Seat", value: "Hand-sculpted saddle" },
      { label: "Finish", value: "Oil and wax" },
    ],
    stock: 40,
    rating: 4.5,
    reviewCount: 38,
    weight: 14,
    dimensions: { width: 19, height: 36, depth: 20 },
    sku: "FSOW-WDC-028",
    createdAt: "2025-03-15T10:00:00Z",
    updatedAt: "2025-08-10T10:00:00Z",
  },
  {
    id: "prod-029",
    name: "Swivel Bar Stool",
    slug: "swivel-bar-stool",
    description:
      "A bar-height swivel stool with a leather-upholstered bucket seat and a polished stainless steel base. The 360-degree swivel and footrest make it ideal for kitchen islands and home bars. Adjustable leveling feet.",
    shortDescription: "Leather bucket-seat swivel bar stool with stainless steel base.",
    price: 399,
    compareAtPrice: 479,
    categoryId: "cat-dining",
    subcategoryId: "sub-bar-stools",
    status: "active",
    featured: false,
    tags: ["leather", "swivel"],
    images: productGallery("swivel-bar-stool"),
    thumbnail: productThumb("swivel-bar-stool"),
    variants: [
      { id: vid(), name: "Tan Leather", type: "color", value: "#D2B48C", priceModifier: 0, stock: 14, sku: "SBS-TL" },
      { id: vid(), name: "Black Leather", type: "color", value: "#1A1A1A", priceModifier: 0, stock: 12, sku: "SBS-BL" },
    ],
    specs: [
      { label: "Seat", value: "Top-grain leather" },
      { label: "Base", value: "Polished stainless steel" },
      { label: "Seat Height", value: '30"' },
      { label: "Swivel", value: "360-degree" },
    ],
    stock: 26,
    rating: 4.6,
    reviewCount: 41,
    weight: 22,
    dimensions: { width: 19, height: 42, depth: 20 },
    sku: "FSOW-SBS-029",
    createdAt: "2025-06-05T10:00:00Z",
    updatedAt: "2025-10-28T10:00:00Z",
  },
  {
    id: "prod-030",
    name: "Oak Sideboard Buffet",
    slug: "oak-sideboard-buffet",
    description:
      "A generously proportioned sideboard in solid white oak with cane-front doors. Three interior compartments with adjustable shelves provide versatile storage for dinnerware, linens, and serving pieces. Topped with a durable lacquered surface.",
    shortDescription: "Solid white oak sideboard with cane-front doors and three compartments.",
    price: 1599,
    compareAtPrice: null,
    categoryId: "cat-dining",
    subcategoryId: "sub-buffets",
    status: "active",
    featured: false,
    tags: ["natural", "cane-detail"],
    images: productGallery("oak-sideboard"),
    thumbnail: productThumb("oak-sideboard"),
    variants: [
      { id: vid(), name: "Natural Oak", type: "material", value: "natural-oak", priceModifier: 0, stock: 7, sku: "OSB-NO" },
    ],
    specs: [
      { label: "Material", value: "Solid white oak, natural cane" },
      { label: "Doors", value: "3, push-to-open" },
      { label: "Shelves", value: "3 adjustable" },
      { label: "Top Surface", value: "Lacquered, heat-resistant" },
    ],
    stock: 7,
    rating: 4.8,
    reviewCount: 19,
    weight: 130,
    dimensions: { width: 68, height: 34, depth: 18 },
    sku: "FSOW-OSB-030",
    createdAt: "2025-07-01T10:00:00Z",
    updatedAt: "2025-11-10T10:00:00Z",
  },
  {
    id: "prod-031",
    name: "Glass China Cabinet",
    slug: "glass-china-cabinet",
    description:
      "An elegant display cabinet with glass doors, glass shelves, and interior LED lighting to showcase your finest dinnerware and collectibles. The solid black cherry frame and brass hardware add a touch of sophistication.",
    shortDescription: "Glass-door display cabinet with LED lighting and cherry frame.",
    price: 1899,
    compareAtPrice: 2199,
    categoryId: "cat-dining",
    subcategoryId: "sub-china-cabinets",
    status: "active",
    featured: false,
    tags: ["display", "led"],
    images: productGallery("glass-china-cabinet"),
    thumbnail: productThumb("glass-china-cabinet"),
    variants: [
      { id: vid(), name: "Cherry/Brass", type: "material", value: "cherry-brass", priceModifier: 0, stock: 4, sku: "GCC-CB" },
      { id: vid(), name: "Black/Chrome", type: "material", value: "black-chrome", priceModifier: 0, stock: 3, sku: "GCC-BC" },
    ],
    specs: [
      { label: "Frame", value: "Solid black cherry" },
      { label: "Glass", value: "Tempered, clear" },
      { label: "Shelves", value: "4 adjustable glass shelves" },
      { label: "Lighting", value: "Integrated LED, dimmable" },
    ],
    stock: 7,
    rating: 4.7,
    reviewCount: 11,
    weight: 175,
    dimensions: { width: 42, height: 78, depth: 16 },
    sku: "FSOW-GCC-031",
    createdAt: "2025-08-15T10:00:00Z",
    updatedAt: "2025-11-22T10:00:00Z",
  },
  // ===== OFFICE =====
  {
    id: "prod-032",
    name: "Standing Desk",
    slug: "standing-desk",
    description:
      "An electric height-adjustable standing desk with a solid bamboo top and dual-motor system. Adjusts smoothly from 25 to 51 inches with programmable memory presets. Built-in cable management tray keeps cords organized.",
    shortDescription: "Electric height-adjustable desk with bamboo top and dual motors.",
    price: 799,
    compareAtPrice: 999,
    categoryId: "cat-office",
    subcategoryId: "sub-desks",
    status: "active",
    featured: true,
    tags: ["bestseller", "ergonomic", "free-shipping"],
    images: productGallery("standing-desk"),
    thumbnail: productThumb("standing-desk"),
    variants: [
      { id: vid(), name: "48\" - Natural Bamboo", type: "size", value: "48-bamboo", priceModifier: 0, stock: 18, sku: "SD-48N" },
      { id: vid(), name: "60\" - Natural Bamboo", type: "size", value: "60-bamboo", priceModifier: 100, stock: 12, sku: "SD-60N" },
      { id: vid(), name: "48\" - Walnut Top", type: "size", value: "48-walnut", priceModifier: 150, stock: 8, sku: "SD-48W" },
      { id: vid(), name: "60\" - Walnut Top", type: "size", value: "60-walnut", priceModifier: 250, stock: 6, sku: "SD-60W" },
    ],
    specs: [
      { label: "Motor", value: "Dual motor, quiet operation (< 45dB)" },
      { label: "Height Range", value: "25\" - 51\"" },
      { label: "Weight Capacity", value: "350 lbs" },
      { label: "Presets", value: "4 programmable memory positions" },
      { label: "Speed", value: "1.5\"/second" },
    ],
    stock: 44,
    rating: 4.7,
    reviewCount: 278,
    weight: 95,
    dimensions: { width: 48, height: 30, depth: 30 },
    sku: "FSOW-SD-032",
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-12-08T10:00:00Z",
  },
  {
    id: "prod-033",
    name: "Ergonomic Office Chair",
    slug: "ergonomic-office-chair",
    description:
      "A fully adjustable ergonomic task chair with breathable mesh back, adjustable lumbar support, 4D armrests, and a waterfall seat edge. Designed for 8+ hours of comfortable sitting. BIFMA certified with a 12-year warranty.",
    shortDescription: "Fully adjustable mesh ergonomic chair with lumbar support and 4D armrests.",
    price: 899,
    compareAtPrice: 1099,
    categoryId: "cat-office",
    subcategoryId: "sub-office-chairs",
    status: "active",
    featured: true,
    tags: ["bestseller", "ergonomic", "warranty"],
    images: productGallery("ergonomic-chair"),
    thumbnail: productThumb("ergonomic-chair"),
    variants: [
      { id: vid(), name: "Black Mesh", type: "color", value: "#1A1A1A", priceModifier: 0, stock: 22, sku: "EOC-BK" },
      { id: vid(), name: "Gray Mesh", type: "color", value: "#808080", priceModifier: 0, stock: 15, sku: "EOC-GR" },
      { id: vid(), name: "Blue Mesh", type: "color", value: "#4169E1", priceModifier: 0, stock: 10, sku: "EOC-BL" },
    ],
    specs: [
      { label: "Back", value: "Breathable mesh with adjustable lumbar" },
      { label: "Armrests", value: "4D adjustable (height, width, depth, angle)" },
      { label: "Seat", value: "High-density foam, waterfall edge" },
      { label: "Certification", value: "BIFMA certified" },
      { label: "Warranty", value: "12 years" },
    ],
    stock: 47,
    rating: 4.6,
    reviewCount: 341,
    weight: 52,
    dimensions: { width: 27, height: 46, depth: 27 },
    sku: "FSOW-EOC-033",
    createdAt: "2025-01-05T10:00:00Z",
    updatedAt: "2025-12-05T10:00:00Z",
  },
  {
    id: "prod-034",
    name: "Writing Desk",
    slug: "writing-desk",
    description:
      "A refined writing desk in solid American cherry with a leather-inlaid writing surface. Two drawers with dovetail joinery provide storage for stationery. The elegant tapered legs and brass drawer pulls complete the classic look.",
    shortDescription: "Solid cherry writing desk with leather inlay and dovetail drawers.",
    price: 1199,
    compareAtPrice: null,
    categoryId: "cat-office",
    subcategoryId: "sub-desks",
    status: "active",
    featured: false,
    tags: ["classic", "handcrafted"],
    images: productGallery("writing-desk"),
    thumbnail: productThumb("writing-desk"),
    variants: [
      { id: vid(), name: "Cherry/Tan Leather", type: "material", value: "cherry-tan", priceModifier: 0, stock: 6, sku: "WD-CT" },
      { id: vid(), name: "Cherry/Green Leather", type: "material", value: "cherry-green", priceModifier: 50, stock: 4, sku: "WD-CG" },
    ],
    specs: [
      { label: "Material", value: "Solid American cherry" },
      { label: "Writing Surface", value: "Full-grain leather inlay" },
      { label: "Drawers", value: "2, dovetail construction" },
      { label: "Hardware", value: "Solid brass pulls" },
    ],
    stock: 10,
    rating: 4.8,
    reviewCount: 16,
    weight: 75,
    dimensions: { width: 48, height: 30, depth: 24 },
    sku: "FSOW-WD-034",
    createdAt: "2025-04-10T10:00:00Z",
    updatedAt: "2025-09-25T10:00:00Z",
  },
  {
    id: "prod-035",
    name: "Executive Office Chair",
    slug: "executive-office-chair",
    description:
      "A premium executive chair upholstered in full-grain leather with a high back, padded headrest, and polished aluminum base. Synchronized tilt mechanism with tension adjustment. Exudes authority and comfort in equal measure.",
    shortDescription: "Full-grain leather executive chair with high back and aluminum base.",
    price: 1299,
    compareAtPrice: 1599,
    categoryId: "cat-office",
    subcategoryId: "sub-office-chairs",
    status: "active",
    featured: false,
    tags: ["premium", "leather"],
    images: productGallery("executive-chair"),
    thumbnail: productThumb("executive-chair"),
    variants: [
      { id: vid(), name: "Black Leather", type: "color", value: "#1A1A1A", priceModifier: 0, stock: 8, sku: "EXC-BK" },
      { id: vid(), name: "Cognac Leather", type: "color", value: "#9A4E1C", priceModifier: 100, stock: 5, sku: "EXC-CG" },
    ],
    specs: [
      { label: "Upholstery", value: "Full-grain leather" },
      { label: "Base", value: "Polished die-cast aluminum" },
      { label: "Tilt", value: "Synchronized mechanism, adjustable tension" },
      { label: "Headrest", value: "Integrated, padded" },
    ],
    stock: 13,
    rating: 4.5,
    reviewCount: 44,
    weight: 58,
    dimensions: { width: 28, height: 50, depth: 28 },
    sku: "FSOW-EXC-035",
    createdAt: "2025-05-15T10:00:00Z",
    updatedAt: "2025-10-20T10:00:00Z",
  },
  {
    id: "prod-036",
    name: "3-Drawer Filing Cabinet",
    slug: "3-drawer-filing-cabinet",
    description:
      "A modern filing cabinet with three deep drawers sized for letter and legal files. Powder-coated steel construction in matte finishes. Locking top drawer secures all three drawers simultaneously. Smooth full-extension ball-bearing slides.",
    shortDescription: "Steel 3-drawer filing cabinet with lock and full-extension slides.",
    price: 349,
    compareAtPrice: null,
    categoryId: "cat-office",
    subcategoryId: "sub-filing-cabinets",
    status: "active",
    featured: false,
    tags: ["storage", "lockable"],
    images: productGallery("filing-cabinet"),
    thumbnail: productThumb("filing-cabinet"),
    variants: [
      { id: vid(), name: "Matte Black", type: "color", value: "#1A1A1A", priceModifier: 0, stock: 20, sku: "FC-MB" },
      { id: vid(), name: "Matte White", type: "color", value: "#F5F5F5", priceModifier: 0, stock: 15, sku: "FC-MW" },
      { id: vid(), name: "Navy", type: "color", value: "#000080", priceModifier: 20, stock: 8, sku: "FC-NV" },
    ],
    specs: [
      { label: "Material", value: "Cold-rolled steel, powder-coated" },
      { label: "Drawers", value: "3, letter/legal compatible" },
      { label: "Lock", value: "Keyed lock, secures all drawers" },
      { label: "Slides", value: "Full-extension ball-bearing" },
    ],
    stock: 43,
    rating: 4.3,
    reviewCount: 58,
    weight: 62,
    dimensions: { width: 15, height: 40, depth: 22 },
    sku: "FSOW-FC-036",
    createdAt: "2025-06-20T10:00:00Z",
    updatedAt: "2025-11-15T10:00:00Z",
  },
  {
    id: "prod-037",
    name: "L-Shaped Desk",
    slug: "l-shaped-desk",
    description:
      "A spacious L-shaped corner desk with a solid walnut veneer top and black steel frame. The generous 60x60 inch layout accommodates dual monitors and peripherals. Integrated cable grommets and a keyboard tray keep your workspace tidy.",
    shortDescription: "Walnut veneer L-shaped desk with steel frame and cable management.",
    price: 999,
    compareAtPrice: 1199,
    categoryId: "cat-office",
    subcategoryId: "sub-desks",
    status: "active",
    featured: false,
    tags: ["spacious", "dual-monitor"],
    images: productGallery("l-shaped-desk"),
    thumbnail: productThumb("l-shaped-desk"),
    variants: [
      { id: vid(), name: "Walnut/Black", type: "material", value: "walnut-black", priceModifier: 0, stock: 10, sku: "LSD-WB" },
      { id: vid(), name: "Oak/White", type: "material", value: "oak-white", priceModifier: 0, stock: 7, sku: "LSD-OW" },
    ],
    specs: [
      { label: "Top", value: "Solid walnut veneer on engineered wood" },
      { label: "Frame", value: "Powder-coated steel" },
      { label: "Dimensions", value: '60" x 60" L-shape' },
      { label: "Features", value: "Cable grommets, keyboard tray" },
    ],
    stock: 17,
    rating: 4.4,
    reviewCount: 73,
    weight: 110,
    dimensions: { width: 60, height: 30, depth: 60 },
    sku: "FSOW-LSD-037",
    createdAt: "2025-07-10T10:00:00Z",
    updatedAt: "2025-11-30T10:00:00Z",
  },
  {
    id: "prod-038",
    name: "Open Bookcase",
    slug: "open-bookcase",
    description:
      "A modern open bookcase with asymmetric shelving for visual interest. Crafted from solid oak with an oil finish. The staggered shelf layout creates a dynamic display while maintaining practical storage.",
    shortDescription: "Solid oak open bookcase with asymmetric shelf design.",
    price: 799,
    compareAtPrice: null,
    categoryId: "cat-office",
    subcategoryId: "sub-bookcases",
    status: "active",
    featured: false,
    tags: ["modern", "display"],
    images: productGallery("open-bookcase"),
    thumbnail: productThumb("open-bookcase"),
    variants: [
      { id: vid(), name: "Natural Oak", type: "material", value: "natural-oak", priceModifier: 0, stock: 12, sku: "OB-NO" },
      { id: vid(), name: "Smoke Oak", type: "material", value: "smoke-oak", priceModifier: 50, stock: 6, sku: "OB-SO" },
    ],
    specs: [
      { label: "Material", value: "Solid European oak" },
      { label: "Shelves", value: "6, asymmetric fixed" },
      { label: "Finish", value: "Natural oil" },
      { label: "Wall Anchor", value: "Included" },
    ],
    stock: 18,
    rating: 4.5,
    reviewCount: 21,
    weight: 80,
    dimensions: { width: 36, height: 72, depth: 12 },
    sku: "FSOW-OB-038",
    createdAt: "2025-08-05T10:00:00Z",
    updatedAt: "2025-11-10T10:00:00Z",
  },
  {
    id: "prod-039",
    name: "Industrial Bookcase",
    slug: "industrial-bookcase",
    description:
      "An industrial-style bookcase combining reclaimed wood shelves with a black pipe frame. Five shelves provide generous storage and display space. The raw, unfinished character adds warmth and authenticity to any office.",
    shortDescription: "Reclaimed wood and black pipe industrial bookcase with 5 shelves.",
    price: 599,
    compareAtPrice: null,
    categoryId: "cat-office",
    subcategoryId: "sub-bookcases",
    status: "archived",
    featured: false,
    tags: ["industrial", "reclaimed"],
    images: productGallery("industrial-bookcase"),
    thumbnail: productThumb("industrial-bookcase"),
    variants: [
      { id: vid(), name: "Reclaimed/Black Pipe", type: "material", value: "reclaimed-pipe", priceModifier: 0, stock: 0, sku: "IB-RP" },
    ],
    specs: [
      { label: "Shelves", value: "Reclaimed pine, 5 fixed" },
      { label: "Frame", value: "Steel pipe, matte black" },
      { label: "Weight Capacity", value: "30 lbs per shelf" },
      { label: "Wall Anchor", value: "Included" },
    ],
    stock: 0,
    rating: 4.1,
    reviewCount: 34,
    weight: 68,
    dimensions: { width: 34, height: 70, depth: 12 },
    sku: "FSOW-IB-039",
    createdAt: "2024-06-01T10:00:00Z",
    updatedAt: "2025-06-01T10:00:00Z",
  },
  // ===== OUTDOOR =====
  {
    id: "prod-040",
    name: "Teak Patio Dining Set",
    slug: "teak-patio-dining-set",
    description:
      "A premium 7-piece outdoor dining set in Grade A teak. Includes a 72-inch rectangular table and 6 folding chairs. Teak naturally weathers to a beautiful silver-gray patina or can be maintained with teak oil for the original honey tone.",
    shortDescription: "Grade A teak 7-piece patio dining set with folding chairs.",
    price: 3999,
    compareAtPrice: 4999,
    categoryId: "cat-outdoor",
    subcategoryId: "sub-patio-sets",
    status: "active",
    featured: true,
    tags: ["premium", "teak", "free-shipping"],
    images: productGallery("teak-patio-set"),
    thumbnail: productThumb("teak-patio-set"),
    variants: [
      { id: vid(), name: "Natural Teak", type: "material", value: "natural-teak", priceModifier: 0, stock: 4, sku: "TPS-NT" },
    ],
    specs: [
      { label: "Material", value: "Grade A plantation teak" },
      { label: "Pieces", value: "1 table + 6 folding chairs" },
      { label: "Table Size", value: '72" x 36"' },
      { label: "Weather", value: "All-weather, no cover needed" },
    ],
    stock: 4,
    rating: 4.9,
    reviewCount: 23,
    weight: 210,
    dimensions: { width: 72, height: 30, depth: 36 },
    sku: "FSOW-TPS-040",
    createdAt: "2025-03-01T10:00:00Z",
    updatedAt: "2025-11-01T10:00:00Z",
  },
  {
    id: "prod-041",
    name: "Outdoor Lounge Chair",
    slug: "outdoor-lounge-chair",
    description:
      "A resort-style outdoor lounge chair with a powder-coated aluminum frame and all-weather Sunbrella cushions. The adjustable back reclines to five positions. Stackable for off-season storage. UV and fade resistant.",
    shortDescription: "Aluminum outdoor lounger with Sunbrella cushions and 5 recline positions.",
    price: 699,
    compareAtPrice: 849,
    categoryId: "cat-outdoor",
    subcategoryId: "sub-lounge-chairs",
    status: "active",
    featured: false,
    tags: ["weather-resistant", "sunbrella"],
    images: productGallery("outdoor-lounge-chair"),
    thumbnail: productThumb("outdoor-lounge-chair"),
    variants: [
      { id: vid(), name: "White/Canvas", type: "color", value: "#F5F5DC", priceModifier: 0, stock: 15, sku: "OLC-WC" },
      { id: vid(), name: "Charcoal/Gray", type: "color", value: "#808080", priceModifier: 0, stock: 10, sku: "OLC-CG" },
    ],
    specs: [
      { label: "Frame", value: "Cast aluminum, powder-coated" },
      { label: "Cushions", value: "Sunbrella solution-dyed acrylic" },
      { label: "Recline", value: "5 positions" },
      { label: "Weather Rating", value: "All-weather, UV resistant" },
    ],
    stock: 25,
    rating: 4.5,
    reviewCount: 57,
    weight: 35,
    dimensions: { width: 28, height: 38, depth: 78 },
    sku: "FSOW-OLC-041",
    createdAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-09-05T10:00:00Z",
  },
  {
    id: "prod-042",
    name: "Wicker Conversation Set",
    slug: "wicker-conversation-set",
    description:
      "A 4-piece outdoor conversation set with all-weather resin wicker over a rust-proof aluminum frame. Includes a loveseat, two club chairs, and a coffee table. Olefin cushions resist moisture, mildew, and fading.",
    shortDescription: "4-piece all-weather wicker conversation set with olefin cushions.",
    price: 1899,
    compareAtPrice: 2299,
    categoryId: "cat-outdoor",
    subcategoryId: "sub-patio-sets",
    status: "active",
    featured: false,
    tags: ["all-weather", "set"],
    images: productGallery("wicker-conversation-set"),
    thumbnail: productThumb("wicker-conversation-set"),
    variants: [
      { id: vid(), name: "Brown/Beige", type: "color", value: "#8B7355", priceModifier: 0, stock: 7, sku: "WCS-BB" },
      { id: vid(), name: "Gray/Blue", type: "color", value: "#708090", priceModifier: 0, stock: 5, sku: "WCS-GB" },
    ],
    specs: [
      { label: "Material", value: "PE resin wicker, aluminum frame" },
      { label: "Pieces", value: "Loveseat + 2 chairs + coffee table" },
      { label: "Cushions", value: "Olefin fabric, removable covers" },
      { label: "Care", value: "Hose clean, no special maintenance" },
    ],
    stock: 12,
    rating: 4.4,
    reviewCount: 42,
    weight: 120,
    dimensions: { width: 80, height: 32, depth: 60 },
    sku: "FSOW-WCS-042",
    createdAt: "2025-03-20T10:00:00Z",
    updatedAt: "2025-08-15T10:00:00Z",
  },
  {
    id: "prod-043",
    name: "Adirondack Chair",
    slug: "adirondack-chair",
    description:
      "A classic Adirondack chair made from recycled high-density polyethylene (HDPE) lumber. Maintenance-free, splinter-free, and built to withstand decades of sun, rain, and snow. Available in a range of coastal-inspired colors.",
    shortDescription: "Recycled HDPE Adirondack chair, maintenance-free and all-weather.",
    price: 399,
    compareAtPrice: null,
    categoryId: "cat-outdoor",
    subcategoryId: "sub-lounge-chairs",
    status: "active",
    featured: false,
    tags: ["sustainable", "recycled", "maintenance-free"],
    images: productGallery("adirondack-chair"),
    thumbnail: productThumb("adirondack-chair"),
    variants: [
      { id: vid(), name: "White", type: "color", value: "#FFFFFF", priceModifier: 0, stock: 20, sku: "ADK-WH" },
      { id: vid(), name: "Navy", type: "color", value: "#000080", priceModifier: 0, stock: 14, sku: "ADK-NV" },
      { id: vid(), name: "Forest Green", type: "color", value: "#228B22", priceModifier: 0, stock: 10, sku: "ADK-FG" },
      { id: vid(), name: "Teak Color", type: "color", value: "#C19A6B", priceModifier: 20, stock: 12, sku: "ADK-TK" },
    ],
    specs: [
      { label: "Material", value: "Recycled HDPE lumber" },
      { label: "Maintenance", value: "None required" },
      { label: "UV", value: "UV-stabilized, fade-resistant" },
      { label: "Warranty", value: "20-year residential" },
    ],
    stock: 56,
    rating: 4.7,
    reviewCount: 198,
    weight: 38,
    dimensions: { width: 30, height: 38, depth: 36 },
    sku: "FSOW-ADK-043",
    createdAt: "2025-02-10T10:00:00Z",
    updatedAt: "2025-10-10T10:00:00Z",
  },
  {
    id: "prod-044",
    name: "Mosaic Bistro Table",
    slug: "mosaic-bistro-table",
    description:
      "A hand-laid ceramic mosaic bistro table with a wrought iron base. The intricate Mediterranean-inspired pattern is crafted from individually placed tiles and sealed for outdoor use. Perfect for balconies, patios, and garden nooks.",
    shortDescription: "Hand-laid ceramic mosaic bistro table with wrought iron base.",
    price: 449,
    compareAtPrice: null,
    categoryId: "cat-outdoor",
    subcategoryId: "sub-garden-tables",
    status: "active",
    featured: false,
    tags: ["handcrafted", "mosaic"],
    images: productGallery("mosaic-bistro-table"),
    thumbnail: productThumb("mosaic-bistro-table"),
    variants: [
      { id: vid(), name: "Blue/White", type: "color", value: "#4169E1", priceModifier: 0, stock: 9, sku: "MBT-BW" },
      { id: vid(), name: "Terracotta/Green", type: "color", value: "#CD853F", priceModifier: 0, stock: 6, sku: "MBT-TG" },
    ],
    specs: [
      { label: "Top", value: "Hand-laid ceramic mosaic, sealed" },
      { label: "Base", value: "Wrought iron, powder-coated" },
      { label: "Diameter", value: '30"' },
      { label: "Care", value: "Cover in freezing weather" },
    ],
    stock: 15,
    rating: 4.6,
    reviewCount: 27,
    weight: 45,
    dimensions: { width: 30, height: 28, depth: 30 },
    sku: "FSOW-MBT-044",
    createdAt: "2025-04-25T10:00:00Z",
    updatedAt: "2025-08-20T10:00:00Z",
  },
  {
    id: "prod-045",
    name: "Cantilever Patio Umbrella",
    slug: "cantilever-patio-umbrella",
    description:
      "A 10-foot cantilever patio umbrella with a 360-degree rotation and adjustable tilt. The Sunbrella canopy provides excellent UV protection while the offset pole design keeps the base out of your seating area. Easy crank lift operation.",
    shortDescription: "10-foot cantilever umbrella with Sunbrella canopy and 360-degree rotation.",
    price: 599,
    compareAtPrice: 749,
    categoryId: "cat-outdoor",
    subcategoryId: "sub-umbrellas",
    status: "active",
    featured: false,
    tags: ["sunbrella", "shade"],
    images: productGallery("cantilever-umbrella"),
    thumbnail: productThumb("cantilever-umbrella"),
    variants: [
      { id: vid(), name: "Natural/White", type: "color", value: "#F5F5DC", priceModifier: 0, stock: 12, sku: "CPU-NW" },
      { id: vid(), name: "Navy Blue", type: "color", value: "#000080", priceModifier: 0, stock: 8, sku: "CPU-NB" },
      { id: vid(), name: "Forest Green", type: "color", value: "#228B22", priceModifier: 0, stock: 6, sku: "CPU-FG" },
    ],
    specs: [
      { label: "Canopy", value: "Sunbrella fabric, UPF 50+" },
      { label: "Size", value: "10-foot diameter" },
      { label: "Rotation", value: "360-degree" },
      { label: "Tilt", value: "Adjustable, infinite positions" },
      { label: "Pole", value: "Powder-coated aluminum" },
    ],
    stock: 26,
    rating: 4.3,
    reviewCount: 65,
    weight: 48,
    dimensions: { width: 120, height: 96, depth: 120 },
    sku: "FSOW-CPU-045",
    createdAt: "2025-03-05T10:00:00Z",
    updatedAt: "2025-09-10T10:00:00Z",
  },
  // ===== DECOR =====
  {
    id: "prod-046",
    name: "Arc Floor Lamp",
    slug: "arc-floor-lamp",
    description:
      "A dramatic arc floor lamp with a brushed brass arm and white linen drum shade. The heavy marble base provides stability while the adjustable arm sweeps gracefully over seating areas. Dimmable with a foot switch.",
    shortDescription: "Brushed brass arc floor lamp with marble base and linen shade.",
    price: 449,
    compareAtPrice: 549,
    categoryId: "cat-decor",
    subcategoryId: "sub-lighting",
    status: "active",
    featured: false,
    tags: ["statement", "dimmable"],
    images: productGallery("arc-floor-lamp"),
    thumbnail: productThumb("arc-floor-lamp"),
    variants: [
      { id: vid(), name: "Brass/White Shade", type: "material", value: "brass-white", priceModifier: 0, stock: 14, sku: "AFL-BW" },
      { id: vid(), name: "Black/Black Shade", type: "material", value: "black-black", priceModifier: 0, stock: 8, sku: "AFL-BB" },
    ],
    specs: [
      { label: "Arm", value: "Brushed brass-finished steel" },
      { label: "Shade", value: "White linen drum, 18\" diameter" },
      { label: "Base", value: "Polished marble" },
      { label: "Bulb", value: "E26, LED compatible (not included)" },
      { label: "Dimmer", value: "Foot switch dimmer" },
    ],
    stock: 22,
    rating: 4.5,
    reviewCount: 76,
    weight: 28,
    dimensions: { width: 44, height: 82, depth: 44 },
    sku: "FSOW-AFL-046",
    createdAt: "2025-05-01T10:00:00Z",
    updatedAt: "2025-10-25T10:00:00Z",
  },
  {
    id: "prod-047",
    name: "Ceramic Table Lamp",
    slug: "ceramic-table-lamp",
    description:
      "A handcrafted ceramic table lamp with an organic textured finish and natural linen shade. Each piece is individually made by artisans, resulting in subtle variations that make every lamp unique. Warm, ambient light for bedside or living room.",
    shortDescription: "Handcrafted ceramic table lamp with textured finish and linen shade.",
    price: 249,
    compareAtPrice: null,
    categoryId: "cat-decor",
    subcategoryId: "sub-lighting",
    status: "active",
    featured: false,
    tags: ["handcrafted", "artisan"],
    images: productGallery("ceramic-table-lamp"),
    thumbnail: productThumb("ceramic-table-lamp"),
    variants: [
      { id: vid(), name: "Ivory", type: "color", value: "#FFFFF0", priceModifier: 0, stock: 20, sku: "CTL-IV" },
      { id: vid(), name: "Sage", type: "color", value: "#B2AC88", priceModifier: 0, stock: 12, sku: "CTL-SG" },
      { id: vid(), name: "Terracotta", type: "color", value: "#E2725B", priceModifier: 0, stock: 8, sku: "CTL-TC" },
    ],
    specs: [
      { label: "Base", value: "Handcrafted stoneware ceramic" },
      { label: "Shade", value: "Natural linen, 14\" diameter" },
      { label: "Bulb", value: "E26, 60W max (not included)" },
      { label: "Switch", value: "Rotary on socket" },
    ],
    stock: 40,
    rating: 4.6,
    reviewCount: 53,
    weight: 8,
    dimensions: { width: 14, height: 24, depth: 14 },
    sku: "FSOW-CTL-047",
    createdAt: "2025-06-10T10:00:00Z",
    updatedAt: "2025-11-05T10:00:00Z",
  },
  {
    id: "prod-048",
    name: "Hand-Knotted Area Rug",
    slug: "hand-knotted-area-rug",
    description:
      "A luxurious hand-knotted wool area rug with an abstract watercolor design in muted earth tones. Made by skilled artisans using centuries-old techniques. The dense pile provides warmth and sound absorption. Available in multiple sizes.",
    shortDescription: "Hand-knotted wool rug with abstract watercolor design in earth tones.",
    price: 1299,
    compareAtPrice: 1599,
    categoryId: "cat-decor",
    subcategoryId: "sub-rugs",
    status: "active",
    featured: false,
    tags: ["handcrafted", "wool", "artisan"],
    images: productGallery("hand-knotted-rug"),
    thumbnail: productThumb("hand-knotted-rug"),
    variants: [
      { id: vid(), name: "5x8 ft", type: "size", value: "5x8", priceModifier: 0, stock: 10, sku: "HKR-58" },
      { id: vid(), name: "8x10 ft", type: "size", value: "8x10", priceModifier: 700, stock: 6, sku: "HKR-810" },
      { id: vid(), name: "9x12 ft", type: "size", value: "9x12", priceModifier: 1200, stock: 4, sku: "HKR-912" },
    ],
    specs: [
      { label: "Material", value: "100% New Zealand wool" },
      { label: "Construction", value: "Hand-knotted, 80 knots/sq inch" },
      { label: "Pile Height", value: '0.5"' },
      { label: "Backing", value: "Cotton" },
      { label: "Origin", value: "India" },
    ],
    stock: 20,
    rating: 4.8,
    reviewCount: 32,
    weight: 45,
    dimensions: { width: 96, height: 1, depth: 60 },
    sku: "FSOW-HKR-048",
    createdAt: "2025-04-05T10:00:00Z",
    updatedAt: "2025-10-30T10:00:00Z",
  },
  {
    id: "prod-049",
    name: "Abstract Canvas Wall Art",
    slug: "abstract-canvas-wall-art",
    description:
      "A large-scale abstract canvas print with vibrant brushstroke textures in a gallery-wrapped format. The giclée printing process captures rich detail and color. Ready to hang with included hardware. A bold focal point for any wall.",
    shortDescription: "Large-scale abstract giclée canvas print, gallery-wrapped and ready to hang.",
    price: 299,
    compareAtPrice: 399,
    categoryId: "cat-decor",
    subcategoryId: "sub-wall-art",
    status: "active",
    featured: false,
    tags: ["abstract", "gallery-wrap"],
    images: productGallery("abstract-wall-art"),
    thumbnail: productThumb("abstract-wall-art"),
    variants: [
      { id: vid(), name: '36" x 48"', type: "size", value: "36x48", priceModifier: 0, stock: 18, sku: "AWA-3648" },
      { id: vid(), name: '48" x 60"', type: "size", value: "48x60", priceModifier: 150, stock: 8, sku: "AWA-4860" },
      { id: vid(), name: '24" x 36"', type: "size", value: "24x36", priceModifier: -100, stock: 25, sku: "AWA-2436" },
    ],
    specs: [
      { label: "Print Method", value: "Giclée on archival canvas" },
      { label: "Wrap", value: "Gallery-wrapped, 1.5\" depth" },
      { label: "Frame", value: "Not required, ready to hang" },
      { label: "UV Protection", value: "UV-resistant inks" },
    ],
    stock: 51,
    rating: 4.3,
    reviewCount: 45,
    weight: 6,
    dimensions: { width: 48, height: 36, depth: 2 },
    sku: "FSOW-AWA-049",
    createdAt: "2025-07-01T10:00:00Z",
    updatedAt: "2025-11-18T10:00:00Z",
  },
  {
    id: "prod-050",
    name: "Concrete Planter Set",
    slug: "concrete-planter-set",
    description:
      "A set of three concrete planters in graduated sizes with a smooth matte finish. Each planter has a drainage hole and matching saucer. The minimalist cylindrical design complements modern and industrial interiors. Suitable for indoor and covered outdoor use.",
    shortDescription: "Set of 3 graduated concrete planters with drainage and saucers.",
    price: 199,
    compareAtPrice: null,
    categoryId: "cat-decor",
    subcategoryId: "sub-planters",
    status: "active",
    featured: false,
    tags: ["set", "concrete", "indoor-outdoor"],
    images: productGallery("concrete-planter-set"),
    thumbnail: productThumb("concrete-planter-set"),
    variants: [
      { id: vid(), name: "Light Gray", type: "color", value: "#D3D3D3", priceModifier: 0, stock: 30, sku: "CPS-LG" },
      { id: vid(), name: "Charcoal", type: "color", value: "#36454F", priceModifier: 0, stock: 18, sku: "CPS-CH" },
      { id: vid(), name: "Terracotta Stain", type: "color", value: "#CD853F", priceModifier: 20, stock: 12, sku: "CPS-TS" },
    ],
    specs: [
      { label: "Material", value: "Fiber-reinforced concrete" },
      { label: "Sizes", value: '6", 8", 10" diameter' },
      { label: "Drainage", value: "Yes, with matching saucers" },
      { label: "Use", value: "Indoor and covered outdoor" },
    ],
    stock: 60,
    rating: 4.4,
    reviewCount: 89,
    weight: 22,
    dimensions: { width: 10, height: 10, depth: 10 },
    sku: "FSOW-CPS-050",
    createdAt: "2025-05-15T10:00:00Z",
    updatedAt: "2025-10-20T10:00:00Z",
  },
];

// ---- Lookup helpers -------------------------------------------------------

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.categoryId === categoryId);
}

export function getProductsBySubcategory(subcategoryId: string): Product[] {
  return products.filter((p) => p.subcategoryId === subcategoryId);
}

export function getActiveProducts(): Product[] {
  return products.filter((p) => p.status === "active");
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured && p.status === "active");
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.tags.some((t) => t.includes(q)),
  );
}

/** All product IDs for cross-referencing from other mock data */
export const productIds = products.map((p) => p.id);
