// ---------------------------------------------------------------------------
// Reviews mock data — 100+ product reviews
// ---------------------------------------------------------------------------

import { avatarImage } from "./images";

// ---- Types ----------------------------------------------------------------

export interface Review {
  id: string;
  productId: string;
  rating: number;
  title: string;
  content: string;
  reviewerName: string;
  reviewerAvatar: string;
  date: string;
  verified: boolean;
  helpful: number;
}

// ---- Data -----------------------------------------------------------------

export const reviews: Review[] = [
  // --- prod-001 Modern Sofa (6 reviews) ---
  {
    id: "rev-001",
    productId: "prod-001",
    rating: 5,
    title: "Absolutely worth every penny",
    content: "We debated for weeks before pulling the trigger on this sofa and I'm so glad we did. The fabric is incredibly soft yet durable — our two cats haven't been able to damage it. Deep seats are perfect for movie nights.",
    reviewerName: "Sarah M.",
    reviewerAvatar: avatarImage("sarah-m"),
    date: "2025-11-15T10:30:00Z",
    verified: true,
    helpful: 24,
  },
  {
    id: "rev-002",
    productId: "prod-001",
    rating: 5,
    title: "Best sofa we've ever owned",
    content: "The quality is immediately apparent when you sit down. Firm enough for support, soft enough to sink into. Delivery was smooth and the team even helped position it in our living room.",
    reviewerName: "James R.",
    reviewerAvatar: avatarImage("james-r"),
    date: "2025-10-22T14:00:00Z",
    verified: true,
    helpful: 18,
  },
  {
    id: "rev-003",
    productId: "prod-001",
    rating: 4,
    title: "Great sofa, minor assembly hiccup",
    content: "Love the look and comfort. Took off one star because the assembly instructions could be clearer — one bolt hole was slightly misaligned but we made it work. Otherwise a fantastic piece.",
    reviewerName: "David L.",
    reviewerAvatar: avatarImage("david-l"),
    date: "2025-09-08T09:45:00Z",
    verified: true,
    helpful: 12,
  },
  {
    id: "rev-004",
    productId: "prod-001",
    rating: 5,
    title: "Compliments every time",
    content: "Every guest who visits asks about this sofa. The color is exactly as shown online and the performance fabric has held up beautifully after six months of daily use.",
    reviewerName: "Emily C.",
    reviewerAvatar: avatarImage("emily-c"),
    date: "2025-08-20T16:15:00Z",
    verified: true,
    helpful: 15,
  },
  {
    id: "rev-005",
    productId: "prod-001",
    rating: 4,
    title: "Comfortable but large",
    content: "Make sure you measure your space carefully. This is a generous sofa and barely fit through our doorway. That said, the comfort level is outstanding and it's become the centerpiece of our living room.",
    reviewerName: "Michael T.",
    reviewerAvatar: avatarImage("michael-t"),
    date: "2025-07-12T11:30:00Z",
    verified: true,
    helpful: 22,
  },
  {
    id: "rev-006",
    productId: "prod-001",
    rating: 3,
    title: "Good quality, cushions need breaking in",
    content: "The build quality is solid and the fabric is premium. However, the cushions were quite firm out of the box and took about two weeks of regular use before they softened up to a comfortable level.",
    reviewerName: "Rachel G.",
    reviewerAvatar: avatarImage("rachel-g"),
    date: "2025-06-05T13:00:00Z",
    verified: true,
    helpful: 8,
  },

  // --- prod-002 Leather Armchair (4 reviews) ---
  {
    id: "rev-007",
    productId: "prod-002",
    rating: 5,
    title: "The leather just gets better",
    content: "Three months in and the leather is developing a gorgeous patina. This chair is my reading spot and it just wraps around you. Truly an investment piece that improves with age.",
    reviewerName: "Robert J.",
    reviewerAvatar: avatarImage("robert-j"),
    date: "2025-11-02T10:00:00Z",
    verified: true,
    helpful: 19,
  },
  {
    id: "rev-008",
    productId: "prod-002",
    rating: 4,
    title: "Beautiful chair, needs break-in",
    content: "The leather is stiff at first — it took about a month before the chair started to feel truly comfortable. But the craftsmanship is impeccable and it's easily the best-looking piece in our den.",
    reviewerName: "Olivia W.",
    reviewerAvatar: avatarImage("olivia-w"),
    date: "2025-10-15T15:30:00Z",
    verified: true,
    helpful: 14,
  },
  {
    id: "rev-009",
    productId: "prod-002",
    rating: 5,
    title: "Exactly what I was looking for",
    content: "Rich cognac color, solid construction, and supremely comfortable. I paired it with a small side table and reading lamp and it's my favorite corner of the house.",
    reviewerName: "Daniel K.",
    reviewerAvatar: avatarImage("daniel-k"),
    date: "2025-09-28T08:45:00Z",
    verified: true,
    helpful: 11,
  },
  {
    id: "rev-010",
    productId: "prod-002",
    rating: 4,
    title: "Stunning but keep pets away",
    content: "Gorgeous chair that elevates our entire room. Word of caution: the leather scratches easily. We had to start keeping the cat out of the den. Quality is top-notch otherwise.",
    reviewerName: "Jessica P.",
    reviewerAvatar: avatarImage("jessica-p"),
    date: "2025-08-10T12:20:00Z",
    verified: true,
    helpful: 16,
  },

  // --- prod-003 Oval Coffee Table (3 reviews) ---
  {
    id: "rev-011",
    productId: "prod-003",
    rating: 5,
    title: "Elegant and functional",
    content: "The oval shape works perfectly in our space — no more bumping into sharp corners. The finish is silky smooth and the proportions are just right for our seating arrangement.",
    reviewerName: "Amanda D.",
    reviewerAvatar: avatarImage("amanda-d"),
    date: "2025-10-30T14:15:00Z",
    verified: true,
    helpful: 9,
  },
  {
    id: "rev-012",
    productId: "prod-003",
    rating: 4,
    title: "Beautiful table, slight wobble",
    content: "Looks absolutely stunning in our living room. There was a very slight wobble when we first assembled it, but adjusting the leveling feet fixed it. Great value for the price.",
    reviewerName: "Chris M.",
    reviewerAvatar: avatarImage("chris-m"),
    date: "2025-09-18T10:00:00Z",
    verified: true,
    helpful: 7,
  },
  {
    id: "rev-013",
    productId: "prod-003",
    rating: 5,
    title: "Perfect living room centerpiece",
    content: "Simple, clean design that goes with everything. The wood grain is gorgeous and each table really does look unique. We get compliments on it constantly.",
    reviewerName: "Lauren B.",
    reviewerAvatar: avatarImage("lauren-b"),
    date: "2025-08-25T16:45:00Z",
    verified: true,
    helpful: 6,
  },

  // --- prod-004 Modular Sectional (4 reviews) ---
  {
    id: "rev-014",
    productId: "prod-004",
    rating: 5,
    title: "So versatile — love the modularity",
    content: "We've rearranged this sectional at least five times since we got it. Movie night configuration, entertaining layout, even split into separate seating for our two rooms. Brilliant concept.",
    reviewerName: "Sophia G.",
    reviewerAvatar: avatarImage("sophia-g"),
    date: "2025-11-20T11:00:00Z",
    verified: true,
    helpful: 28,
  },
  {
    id: "rev-015",
    productId: "prod-004",
    rating: 4,
    title: "Premium quality modular sofa",
    content: "The pieces connect solidly and the fabric is luxurious. My only wish is that they offered more color options. The grey we chose is nice but I would have loved a deep navy.",
    reviewerName: "Kevin H.",
    reviewerAvatar: avatarImage("kevin-h"),
    date: "2025-10-05T09:30:00Z",
    verified: true,
    helpful: 10,
  },
  {
    id: "rev-016",
    productId: "prod-004",
    rating: 5,
    title: "Worth the investment",
    content: "We saved for months for this sectional and it was absolutely worth the wait. The quality is evident in every stitch. Seats are deep and comfortable, and the modular design means it will work in our next home too.",
    reviewerName: "Tyler A.",
    reviewerAvatar: avatarImage("tyler-a"),
    date: "2025-09-12T14:45:00Z",
    verified: true,
    helpful: 20,
  },
  {
    id: "rev-017",
    productId: "prod-004",
    rating: 4,
    title: "Great but delivery took a while",
    content: "The sofa itself is incredible — super comfortable and well-made. Delivery took three weeks longer than estimated though, which was frustrating. Once it arrived, all was forgiven.",
    reviewerName: "Natalie Y.",
    reviewerAvatar: avatarImage("natalie-y"),
    date: "2025-08-01T10:15:00Z",
    verified: true,
    helpful: 7,
  },

  // --- prod-005 Tall Bookshelf (3 reviews) ---
  {
    id: "rev-018",
    productId: "prod-005",
    rating: 4,
    title: "Sleek and sturdy",
    content: "Holds a lot of books without looking bulky. The A-frame design gives it a modern feel. Make sure to anchor it to the wall as recommended — it's tall and needs the support.",
    reviewerName: "Andrew W.",
    reviewerAvatar: avatarImage("andrew-w"),
    date: "2025-10-18T16:00:00Z",
    verified: true,
    helpful: 8,
  },
  {
    id: "rev-019",
    productId: "prod-005",
    rating: 5,
    title: "Exactly as pictured",
    content: "So happy with this purchase. The wood is beautiful and the shelves are generously spaced. It holds all my books, photos, and plants with room to spare.",
    reviewerName: "Hannah S.",
    reviewerAvatar: avatarImage("hannah-s"),
    date: "2025-09-05T11:30:00Z",
    verified: true,
    helpful: 5,
  },
  {
    id: "rev-020",
    productId: "prod-005",
    rating: 4,
    title: "Good bookshelf, tricky assembly",
    content: "Assembly took about 90 minutes with two people. Some of the screw holes needed a bit of persuasion. End result looks great though and it's very stable once secured to the wall.",
    reviewerName: "Brandon K.",
    reviewerAvatar: avatarImage("brandon-k"),
    date: "2025-07-22T13:45:00Z",
    verified: true,
    helpful: 11,
  },

  // --- prod-007 Glass Coffee Table (3 reviews) ---
  {
    id: "rev-021",
    productId: "prod-007",
    rating: 5,
    title: "A showpiece",
    content: "The glass top catches the light beautifully. It makes our living room feel more open and spacious. Fingerprints show easily but a quick wipe keeps it pristine.",
    reviewerName: "Megan T.",
    reviewerAvatar: avatarImage("megan-t"),
    date: "2025-11-08T10:00:00Z",
    verified: true,
    helpful: 13,
  },
  {
    id: "rev-022",
    productId: "prod-007",
    rating: 4,
    title: "Beautiful but needs constant cleaning",
    content: "Absolutely gorgeous table that opens up the room. You just have to accept that it needs cleaning almost daily if you want it looking its best. The tempered glass feels very solid.",
    reviewerName: "Jason B.",
    reviewerAvatar: avatarImage("jason-b"),
    date: "2025-10-01T15:00:00Z",
    verified: true,
    helpful: 9,
  },
  {
    id: "rev-023",
    productId: "prod-007",
    rating: 5,
    title: "Transformed our living room",
    content: "Replaced a bulky wooden table with this one and the difference is remarkable. The room feels twice as big. Build quality is excellent and the edges are smoothly finished.",
    reviewerName: "Stephanie W.",
    reviewerAvatar: avatarImage("stephanie-w"),
    date: "2025-08-15T12:30:00Z",
    verified: true,
    helpful: 6,
  },

  // --- prod-010 Floating TV Console (3 reviews) ---
  {
    id: "rev-024",
    productId: "prod-010",
    rating: 5,
    title: "Sleek and space-saving",
    content: "The floating design makes vacuuming underneath a dream. Cable management is excellent — everything is hidden behind the unit. Installation was straightforward with the included hardware.",
    reviewerName: "Ryan H.",
    reviewerAvatar: avatarImage("ryan-h"),
    date: "2025-11-25T09:00:00Z",
    verified: true,
    helpful: 17,
  },
  {
    id: "rev-025",
    productId: "prod-010",
    rating: 4,
    title: "Great console, tricky installation",
    content: "Beautiful piece once mounted. The wall installation required finding studs and having the right tools. I'd recommend hiring a handyman if you're not comfortable with wall mounting.",
    reviewerName: "Nicole A.",
    reviewerAvatar: avatarImage("nicole-a"),
    date: "2025-10-12T14:30:00Z",
    verified: true,
    helpful: 12,
  },
  {
    id: "rev-026",
    productId: "prod-010",
    rating: 4,
    title: "Modern and clean",
    content: "Exactly the minimalist look we wanted. Holds our 55-inch TV perfectly with room for a soundbar. The soft-close doors are a nice touch.",
    reviewerName: "Matthew L.",
    reviewerAvatar: avatarImage("matthew-l"),
    date: "2025-09-20T11:15:00Z",
    verified: false,
    helpful: 4,
  },

  // --- prod-013 Upholstered Bed Frame (5 reviews) ---
  {
    id: "rev-027",
    productId: "prod-013",
    rating: 5,
    title: "Our bedroom feels like a hotel",
    content: "This bed completely transformed our bedroom. The upholstered headboard is perfect for sitting up and reading. No squeaks, no wobbles — just solid comfort night after night.",
    reviewerName: "Kayla W.",
    reviewerAvatar: avatarImage("kayla-w"),
    date: "2025-11-30T10:00:00Z",
    verified: true,
    helpful: 21,
  },
  {
    id: "rev-028",
    productId: "prod-013",
    rating: 5,
    title: "Gorgeous and well-made",
    content: "The linen fabric feels luxurious and the platform slats eliminated the need for a box spring. Assembly took about an hour with two people. No regrets at all.",
    reviewerName: "Sarah M.",
    reviewerAvatar: avatarImage("sarah-m-2"),
    date: "2025-10-28T16:00:00Z",
    verified: true,
    helpful: 16,
  },
  {
    id: "rev-029",
    productId: "prod-013",
    rating: 4,
    title: "Beautiful bed, firm slats",
    content: "The bed looks incredible. The slats are on the firm side which is actually great for back support. I paired it with a medium-soft mattress and the combination is perfect.",
    reviewerName: "Chris M.",
    reviewerAvatar: avatarImage("chris-m-2"),
    date: "2025-09-15T08:30:00Z",
    verified: true,
    helpful: 10,
  },
  {
    id: "rev-030",
    productId: "prod-013",
    rating: 5,
    title: "Five stars — no hesitation",
    content: "From unboxing to assembly to first night's sleep — everything about this bed exceeded expectations. The headboard is tall and dramatic, exactly what I wanted. Highly recommended.",
    reviewerName: "Ashley C.",
    reviewerAvatar: avatarImage("ashley-c"),
    date: "2025-08-22T14:15:00Z",
    verified: true,
    helpful: 13,
  },
  {
    id: "rev-031",
    productId: "prod-013",
    rating: 4,
    title: "Great bed, slow delivery",
    content: "The bed is absolutely beautiful and well-constructed. Delivery was delayed by about 10 days which was annoying, but the product itself is worth the wait.",
    reviewerName: "Marcus H.",
    reviewerAvatar: avatarImage("marcus-h"),
    date: "2025-07-10T10:45:00Z",
    verified: true,
    helpful: 5,
  },

  // --- prod-014 Walnut Nightstand (3 reviews) ---
  {
    id: "rev-032",
    productId: "prod-014",
    rating: 5,
    title: "Perfect companion for the bed",
    content: "Paired these with the upholstered bed frame and they look amazing together. The drawer is deep enough for essentials and the soft-close mechanism is silky smooth.",
    reviewerName: "Emily C.",
    reviewerAvatar: avatarImage("emily-c-2"),
    date: "2025-11-12T09:30:00Z",
    verified: true,
    helpful: 8,
  },
  {
    id: "rev-033",
    productId: "prod-014",
    rating: 4,
    title: "Beautiful walnut grain",
    content: "The wood grain on our nightstand is absolutely stunning. Every piece is truly unique. Small enough not to crowd the bedroom but practical with the drawer and shelf.",
    reviewerName: "David L.",
    reviewerAvatar: avatarImage("david-l-2"),
    date: "2025-10-05T15:45:00Z",
    verified: true,
    helpful: 6,
  },
  {
    id: "rev-034",
    productId: "prod-014",
    rating: 5,
    title: "Solid craftsmanship",
    content: "You can feel the quality the moment you open the drawer. Dovetail joints, smooth slides, warm walnut finish. This is furniture that will last for decades.",
    reviewerName: "Robert J.",
    reviewerAvatar: avatarImage("robert-j-2"),
    date: "2025-09-02T11:00:00Z",
    verified: true,
    helpful: 10,
  },

  // --- prod-015 6-Drawer Dresser (3 reviews) ---
  {
    id: "rev-035",
    productId: "prod-015",
    rating: 5,
    title: "Massive storage, beautiful design",
    content: "This dresser is a workhorse. Six deep drawers hold more than I expected, and the full-extension slides mean nothing gets lost at the back. The wood finish is warm and rich.",
    reviewerName: "Olivia W.",
    reviewerAvatar: avatarImage("olivia-w-2"),
    date: "2025-11-18T13:00:00Z",
    verified: true,
    helpful: 14,
  },
  {
    id: "rev-036",
    productId: "prod-015",
    rating: 4,
    title: "Heavy but worth it",
    content: "This thing is HEAVY — needed three people to get it upstairs. But once in place, it's rock-solid and looks absolutely premium. The drawers glide beautifully.",
    reviewerName: "Brian W.",
    reviewerAvatar: avatarImage("brian-w"),
    date: "2025-10-08T10:15:00Z",
    verified: true,
    helpful: 11,
  },
  {
    id: "rev-037",
    productId: "prod-015",
    rating: 5,
    title: "Heirloom quality",
    content: "This is the kind of furniture you pass down to your kids. Solid wood throughout, no particle board in sight. The brass pulls are a nice elegant touch.",
    reviewerName: "Amanda D.",
    reviewerAvatar: avatarImage("amanda-d-2"),
    date: "2025-09-22T16:30:00Z",
    verified: true,
    helpful: 9,
  },

  // --- prod-022 Hybrid Mattress (5 reviews) ---
  {
    id: "rev-038",
    productId: "prod-022",
    rating: 5,
    title: "Best sleep of my life",
    content: "I was skeptical about buying a mattress online but the 100-night trial gave me confidence. After two months, I can say this is hands down the best mattress I've ever slept on. Perfect balance of support and softness.",
    reviewerName: "James R.",
    reviewerAvatar: avatarImage("james-r-2"),
    date: "2025-12-01T10:00:00Z",
    verified: true,
    helpful: 32,
  },
  {
    id: "rev-039",
    productId: "prod-022",
    rating: 5,
    title: "No more back pain",
    content: "After years of waking up with a sore back, this mattress has been life-changing. The pocket coils provide amazing support and the memory foam layer cushions pressure points. I wish I'd bought it sooner.",
    reviewerName: "Michael T.",
    reviewerAvatar: avatarImage("michael-t-2"),
    date: "2025-11-15T08:00:00Z",
    verified: true,
    helpful: 27,
  },
  {
    id: "rev-040",
    productId: "prod-022",
    rating: 4,
    title: "Great mattress, slight off-gassing",
    content: "Sleep quality is excellent and the construction feels premium. There was a slight chemical smell when first unpacked that took about 3 days to fully dissipate. After that, perfection.",
    reviewerName: "Lauren B.",
    reviewerAvatar: avatarImage("lauren-b-2"),
    date: "2025-10-20T14:30:00Z",
    verified: true,
    helpful: 18,
  },
  {
    id: "rev-041",
    productId: "prod-022",
    rating: 5,
    title: "Couples love it",
    content: "My partner and I have very different sleep preferences — I like firm, she likes soft. This hybrid somehow works for both of us. Zero motion transfer too, which is amazing.",
    reviewerName: "Daniel K.",
    reviewerAvatar: avatarImage("daniel-k-2"),
    date: "2025-09-30T11:45:00Z",
    verified: true,
    helpful: 21,
  },
  {
    id: "rev-042",
    productId: "prod-022",
    rating: 4,
    title: "Excellent value for the quality",
    content: "Compared to similar mattresses from premium brands, this is an incredible value. The organic cotton cover is soft and breathable. Only wish it came with a waterproof protector.",
    reviewerName: "Sophia G.",
    reviewerAvatar: avatarImage("sophia-g-2"),
    date: "2025-08-12T10:00:00Z",
    verified: true,
    helpful: 15,
  },

  // --- prod-023 Extendable Dining Table (3 reviews) ---
  {
    id: "rev-043",
    productId: "prod-023",
    rating: 5,
    title: "Perfect for entertaining",
    content: "Hosted Thanksgiving for 10 people and this table was incredible. The extension mechanism is smooth and the table looks gorgeous when fully extended. Solid oak that will last forever.",
    reviewerName: "Stephanie W.",
    reviewerAvatar: avatarImage("stephanie-w-2"),
    date: "2025-12-02T16:00:00Z",
    verified: true,
    helpful: 19,
  },
  {
    id: "rev-044",
    productId: "prod-023",
    rating: 4,
    title: "Great table, one concern",
    content: "The table itself is beautiful and the extension works well. My only concern is that the leaf leaves a visible seam when extended. It's minor but noticeable if you're looking for it.",
    reviewerName: "Kevin H.",
    reviewerAvatar: avatarImage("kevin-h-2"),
    date: "2025-10-25T09:30:00Z",
    verified: true,
    helpful: 8,
  },
  {
    id: "rev-045",
    productId: "prod-023",
    rating: 5,
    title: "Daily table, party table",
    content: "Works perfectly as our everyday four-person table, then transforms for dinner parties. The butterfly mechanism stores neatly inside. No sagging in the middle when extended.",
    reviewerName: "Ryan H.",
    reviewerAvatar: avatarImage("ryan-h-2"),
    date: "2025-09-08T13:15:00Z",
    verified: true,
    helpful: 12,
  },

  // --- prod-024 Upholstered Dining Chair (3 reviews) ---
  {
    id: "rev-046",
    productId: "prod-024",
    rating: 5,
    title: "Comfortable for long dinners",
    content: "These chairs encourage lingering at the table. The upholstered seat makes multi-course dinners comfortable and the ash frame is lightweight enough to move easily.",
    reviewerName: "Nicole A.",
    reviewerAvatar: avatarImage("nicole-a-2"),
    date: "2025-11-05T10:30:00Z",
    verified: true,
    helpful: 11,
  },
  {
    id: "rev-047",
    productId: "prod-024",
    rating: 4,
    title: "Great value, sold in pairs",
    content: "The price for a set of two is excellent. The chairs are well-made and comfortable. The fabric cleans easily with a damp cloth. We bought three sets for our dining table.",
    reviewerName: "Andrew W.",
    reviewerAvatar: avatarImage("andrew-w-2"),
    date: "2025-10-18T15:00:00Z",
    verified: true,
    helpful: 7,
  },
  {
    id: "rev-048",
    productId: "prod-024",
    rating: 4,
    title: "Lovely Scandinavian design",
    content: "These chairs perfectly complement our oak dining table. The curved back is surprisingly supportive. Only suggestion: they could use slightly thicker padding on the seat.",
    reviewerName: "Megan T.",
    reviewerAvatar: avatarImage("megan-t-2"),
    date: "2025-09-25T12:00:00Z",
    verified: true,
    helpful: 5,
  },

  // --- prod-025 Round Dining Table (2 reviews) ---
  {
    id: "rev-049",
    productId: "prod-025",
    rating: 5,
    title: "Stunning marble top",
    content: "The marble veining on ours is absolutely beautiful — like a piece of art. The pedestal base is solid and doesn't wobble at all. We use it for daily meals and it still looks pristine.",
    reviewerName: "Hannah S.",
    reviewerAvatar: avatarImage("hannah-s-2"),
    date: "2025-11-22T11:00:00Z",
    verified: true,
    helpful: 14,
  },
  {
    id: "rev-050",
    productId: "prod-025",
    rating: 4,
    title: "Beautiful but needs care",
    content: "Absolutely gorgeous table. Just be aware that marble requires more maintenance than wood — you need to seal it regularly and be careful with acidic foods and drinks. Worth it for the look.",
    reviewerName: "Jessica P.",
    reviewerAvatar: avatarImage("jessica-p-2"),
    date: "2025-10-10T14:45:00Z",
    verified: true,
    helpful: 16,
  },

  // --- prod-032 Standing Desk (5 reviews) ---
  {
    id: "rev-051",
    productId: "prod-032",
    rating: 5,
    title: "Game-changer for WFH",
    content: "I stand for about 4 hours a day now and my back pain has completely disappeared. The dual motors are whisper-quiet and the height presets make switching positions effortless. The bamboo top is beautiful.",
    reviewerName: "Tyler A.",
    reviewerAvatar: avatarImage("tyler-a-2"),
    date: "2025-12-05T09:00:00Z",
    verified: true,
    helpful: 35,
  },
  {
    id: "rev-052",
    productId: "prod-032",
    rating: 5,
    title: "Best desk purchase ever",
    content: "Four programmable presets, smooth and quiet motor, and a gorgeous bamboo top. I use it every day for 8+ hours and it's been flawless. The cable management tray keeps everything tidy.",
    reviewerName: "Chris M.",
    reviewerAvatar: avatarImage("chris-m-3"),
    date: "2025-11-10T14:00:00Z",
    verified: true,
    helpful: 24,
  },
  {
    id: "rev-053",
    productId: "prod-032",
    rating: 4,
    title: "Great desk, finicky controller",
    content: "The desk itself is excellent — sturdy, smooth, and well-built. The digital controller can be a bit finicky to program. Once you figure it out though, it's incredibly convenient.",
    reviewerName: "Kayla W.",
    reviewerAvatar: avatarImage("kayla-w-2"),
    date: "2025-10-22T10:30:00Z",
    verified: true,
    helpful: 12,
  },
  {
    id: "rev-054",
    productId: "prod-032",
    rating: 5,
    title: "Upgraded from a cheap standing desk",
    content: "Night and day difference compared to my previous budget standing desk. The dual motors handle the weight of two monitors, laptop, and accessories without any wobble. Worth every cent.",
    reviewerName: "Marcus H.",
    reviewerAvatar: avatarImage("marcus-h-2"),
    date: "2025-09-18T16:15:00Z",
    verified: true,
    helpful: 18,
  },
  {
    id: "rev-055",
    productId: "prod-032",
    rating: 4,
    title: "Solid construction, long assembly",
    content: "Budget about 90 minutes for assembly — it's straightforward but there are a lot of parts. Once assembled, it's rock solid at any height. The bamboo top is a standout feature.",
    reviewerName: "Jason B.",
    reviewerAvatar: avatarImage("jason-b-2"),
    date: "2025-08-05T11:00:00Z",
    verified: true,
    helpful: 9,
  },

  // --- prod-033 Ergonomic Office Chair (5 reviews) ---
  {
    id: "rev-056",
    productId: "prod-033",
    rating: 5,
    title: "Worth every penny for your back",
    content: "As someone who works 10-hour days at a desk, this chair has been a revelation. The adjustable lumbar support actually works, the mesh keeps me cool, and the 4D armrests are positioned perfectly.",
    reviewerName: "David L.",
    reviewerAvatar: avatarImage("david-l-3"),
    date: "2025-12-08T10:00:00Z",
    verified: true,
    helpful: 38,
  },
  {
    id: "rev-057",
    productId: "prod-033",
    rating: 5,
    title: "Office chair perfection",
    content: "I've tried chairs three times this price and this one beats them all. The mesh back is incredibly breathable — no more sweaty back during summer. Assembly took 20 minutes.",
    reviewerName: "Sarah M.",
    reviewerAvatar: avatarImage("sarah-m-3"),
    date: "2025-11-20T15:30:00Z",
    verified: true,
    helpful: 25,
  },
  {
    id: "rev-058",
    productId: "prod-033",
    rating: 4,
    title: "Great chair, seat could be softer",
    content: "The back support and armrests are phenomenal. The seat cushion is on the firm side — it's supportive but I wish it had a bit more padding for long days. Overall still the best chair I've owned.",
    reviewerName: "Brandon K.",
    reviewerAvatar: avatarImage("brandon-k-2"),
    date: "2025-10-15T09:45:00Z",
    verified: true,
    helpful: 14,
  },
  {
    id: "rev-059",
    productId: "prod-033",
    rating: 5,
    title: "Chiropractor approved",
    content: "My chiropractor actually recommended this brand. After three months, my posture has improved noticeably and I no longer need as many adjustments. The 12-year warranty gives great peace of mind.",
    reviewerName: "Natalie Y.",
    reviewerAvatar: avatarImage("natalie-y-2"),
    date: "2025-09-28T13:00:00Z",
    verified: true,
    helpful: 22,
  },
  {
    id: "rev-060",
    productId: "prod-033",
    rating: 4,
    title: "Excellent chair, too many adjustments",
    content: "There are so many adjustment options that it took me a week to find my ideal setup. Once dialed in though, it's incredibly comfortable. I'd recommend spending time with the setup guide.",
    reviewerName: "Matthew L.",
    reviewerAvatar: avatarImage("matthew-l-2"),
    date: "2025-08-18T10:30:00Z",
    verified: true,
    helpful: 10,
  },

  // --- prod-034 Writing Desk (2 reviews) ---
  {
    id: "rev-061",
    productId: "prod-034",
    rating: 5,
    title: "A writer's dream desk",
    content: "The leather inlay is gorgeous and so pleasant to write on. This desk inspires me to actually sit down and work. The three drawers hold all my stationery and supplies neatly.",
    reviewerName: "Emily C.",
    reviewerAvatar: avatarImage("emily-c-3"),
    date: "2025-11-02T09:00:00Z",
    verified: true,
    helpful: 8,
  },
  {
    id: "rev-062",
    productId: "prod-034",
    rating: 4,
    title: "Classic and elegant",
    content: "This desk has old-world charm that's hard to find today. The brass-tipped legs are a beautiful detail. Only note: it's a dedicated writing desk, not a computer desk — plan accordingly for your setup.",
    reviewerName: "Robert J.",
    reviewerAvatar: avatarImage("robert-j-3"),
    date: "2025-09-10T14:30:00Z",
    verified: true,
    helpful: 6,
  },

  // --- prod-040 Teak Patio Dining Set (3 reviews) ---
  {
    id: "rev-063",
    productId: "prod-040",
    rating: 5,
    title: "Survived its first winter beautifully",
    content: "Left the set outside through rain, snow, and sun. The teak has started to develop that beautiful silver patina and the structure is as solid as day one. Grade-A teak is worth the premium.",
    reviewerName: "Olivia W.",
    reviewerAvatar: avatarImage("olivia-w-3"),
    date: "2025-11-28T10:00:00Z",
    verified: true,
    helpful: 22,
  },
  {
    id: "rev-064",
    productId: "prod-040",
    rating: 4,
    title: "Excellent quality outdoor furniture",
    content: "The teak is heavy and feels incredibly solid. Chairs stack nicely for storage. Only downside is the initial cost, but when you consider how long this will last, it's actually a great investment.",
    reviewerName: "Jason B.",
    reviewerAvatar: avatarImage("jason-b-3"),
    date: "2025-10-05T14:00:00Z",
    verified: true,
    helpful: 13,
  },
  {
    id: "rev-065",
    productId: "prod-040",
    rating: 5,
    title: "Al fresco dining at its finest",
    content: "We've eaten dinner outside every night since this set arrived. The table is generous enough for a full spread and the chairs are surprisingly comfortable without cushions.",
    reviewerName: "Daniel K.",
    reviewerAvatar: avatarImage("daniel-k-3"),
    date: "2025-08-22T18:00:00Z",
    verified: true,
    helpful: 9,
  },

  // --- prod-041 Outdoor Lounge Chair (2 reviews) ---
  {
    id: "rev-066",
    productId: "prod-041",
    rating: 4,
    title: "Pool days sorted",
    content: "Five reclining positions is perfect — from upright reading to fully flat sunbathing. The wheels make it easy to chase the shade. Wish it came with a cushion, but the teak itself is comfortable.",
    reviewerName: "Ashley C.",
    reviewerAvatar: avatarImage("ashley-c-2"),
    date: "2025-10-30T11:30:00Z",
    verified: true,
    helpful: 7,
  },
  {
    id: "rev-067",
    productId: "prod-041",
    rating: 5,
    title: "Built to last a lifetime",
    content: "This is the kind of outdoor furniture your grandparents would have bought. Solid teak, stainless hardware, smooth reclining mechanism. Absolute luxury by the pool.",
    reviewerName: "Sophia G.",
    reviewerAvatar: avatarImage("sophia-g-3"),
    date: "2025-09-15T16:45:00Z",
    verified: true,
    helpful: 11,
  },

  // --- prod-043 Adirondack Chair (4 reviews) ---
  {
    id: "rev-068",
    productId: "prod-043",
    rating: 5,
    title: "Zero maintenance perfection",
    content: "Recycled HDPE is the way to go for outdoor furniture. No painting, no staining, no rot. These chairs look as good as the day we bought them after a full year outside.",
    reviewerName: "Chris M.",
    reviewerAvatar: avatarImage("chris-m-4"),
    date: "2025-12-10T10:00:00Z",
    verified: true,
    helpful: 20,
  },
  {
    id: "rev-069",
    productId: "prod-043",
    rating: 5,
    title: "Classic look, modern material",
    content: "Love that these are made from recycled materials. The navy color is vibrant and the chair is incredibly comfortable. We bought four for our fire pit area and they look fantastic.",
    reviewerName: "Lauren B.",
    reviewerAvatar: avatarImage("lauren-b-3"),
    date: "2025-11-05T14:15:00Z",
    verified: true,
    helpful: 15,
  },
  {
    id: "rev-070",
    productId: "prod-043",
    rating: 4,
    title: "Heavier than expected",
    content: "These chairs are surprisingly heavy — about 40 pounds each. That's actually a good thing for stability in the wind, but don't expect to move them around casually. Very comfortable once seated.",
    reviewerName: "Tyler A.",
    reviewerAvatar: avatarImage("tyler-a-3"),
    date: "2025-09-20T10:00:00Z",
    verified: true,
    helpful: 8,
  },
  {
    id: "rev-071",
    productId: "prod-043",
    rating: 4,
    title: "Eco-friendly and sturdy",
    content: "Feels good knowing these are made from recycled materials. They've held up through multiple rainstorms and still look brand new. The sage green pairs beautifully with our garden.",
    reviewerName: "Hannah S.",
    reviewerAvatar: avatarImage("hannah-s-3"),
    date: "2025-08-08T12:30:00Z",
    verified: true,
    helpful: 6,
  },

  // --- prod-046 Arc Floor Lamp (3 reviews) ---
  {
    id: "rev-072",
    productId: "prod-046",
    rating: 5,
    title: "Statement lighting at its best",
    content: "This lamp transforms the entire mood of our living room. The arc extends perfectly over our reading corner and the marble base is heavy enough that it never tips. The brass patina is developing nicely.",
    reviewerName: "Megan T.",
    reviewerAvatar: avatarImage("megan-t-3"),
    date: "2025-11-15T09:30:00Z",
    verified: true,
    helpful: 17,
  },
  {
    id: "rev-073",
    productId: "prod-046",
    rating: 4,
    title: "Beautiful lamp, heavy base",
    content: "The lamp is gorgeous and throws warm light perfectly over the sofa. The marble base is extremely heavy though — plan to position it once and leave it. Moving it around is not practical.",
    reviewerName: "Kevin H.",
    reviewerAvatar: avatarImage("kevin-h-3"),
    date: "2025-10-02T15:00:00Z",
    verified: true,
    helpful: 10,
  },
  {
    id: "rev-074",
    productId: "prod-046",
    rating: 5,
    title: "Instagram-worthy lamp",
    content: "Every photo of our living room gets comments about this lamp. It's the finishing touch that ties the whole room together. Build quality matches the visual appeal — no cheap materials here.",
    reviewerName: "Natalie Y.",
    reviewerAvatar: avatarImage("natalie-y-3"),
    date: "2025-09-08T11:00:00Z",
    verified: true,
    helpful: 13,
  },

  // --- prod-048 Hand-Knotted Area Rug (3 reviews) ---
  {
    id: "rev-075",
    productId: "prod-048",
    rating: 5,
    title: "Worth every cent",
    content: "You can feel the quality the moment your feet touch this rug. The wool is incredibly soft and the geometric pattern adds sophistication without being overwhelming. It anchors our living room perfectly.",
    reviewerName: "Jessica P.",
    reviewerAvatar: avatarImage("jessica-p-3"),
    date: "2025-12-05T10:00:00Z",
    verified: true,
    helpful: 16,
  },
  {
    id: "rev-076",
    productId: "prod-048",
    rating: 5,
    title: "Artisan quality you can see",
    content: "Knowing that someone spent 200+ hours hand-knotting this rug makes it even more special. The ivory/grey palette goes with everything and the pile is luxuriously thick.",
    reviewerName: "Sarah M.",
    reviewerAvatar: avatarImage("sarah-m-4"),
    date: "2025-10-28T14:30:00Z",
    verified: true,
    helpful: 12,
  },
  {
    id: "rev-077",
    productId: "prod-048",
    rating: 4,
    title: "Beautiful rug, some shedding",
    content: "The rug is gorgeous and the quality is undeniable. It does shed quite a bit during the first few weeks — our vacuum was full after every session. It's mostly stopped now and the rug looks amazing.",
    reviewerName: "Amanda D.",
    reviewerAvatar: avatarImage("amanda-d-3"),
    date: "2025-09-12T10:15:00Z",
    verified: true,
    helpful: 19,
  },

  // --- prod-006 Velvet Accent Chair (3 reviews) ---
  {
    id: "rev-078",
    productId: "prod-006",
    rating: 5,
    title: "Stunning accent piece",
    content: "The emerald velvet is even more gorgeous in person. This chair instantly elevated our bedroom corner into a cozy reading nook. Surprisingly comfortable for an accent chair.",
    reviewerName: "Rachel G.",
    reviewerAvatar: avatarImage("rachel-g-2"),
    date: "2025-11-10T11:00:00Z",
    verified: true,
    helpful: 14,
  },
  {
    id: "rev-079",
    productId: "prod-006",
    rating: 4,
    title: "Beautiful but attracts lint",
    content: "Velvet is a lint magnet — be prepared with a lint roller. The chair itself is beautiful and comfortable, with excellent construction. The brass legs are a premium touch.",
    reviewerName: "Kayla W.",
    reviewerAvatar: avatarImage("kayla-w-3"),
    date: "2025-10-20T14:00:00Z",
    verified: true,
    helpful: 11,
  },
  {
    id: "rev-080",
    productId: "prod-006",
    rating: 5,
    title: "Designer look for less",
    content: "Looks like it belongs in a magazine spread. We get so many compliments on this chair. It's solidly built and the velvet hasn't shown any wear after four months of regular use.",
    reviewerName: "Nicole A.",
    reviewerAvatar: avatarImage("nicole-a-3"),
    date: "2025-09-05T09:30:00Z",
    verified: true,
    helpful: 8,
  },

  // --- prod-008 Mid-Century TV Stand (2 reviews) ---
  {
    id: "rev-081",
    productId: "prod-008",
    rating: 4,
    title: "Retro charm with modern function",
    content: "The mid-century design pairs perfectly with our vintage-inspired living room. Cable management could be better but the overall build quality and aesthetic are spot-on.",
    reviewerName: "Matthew L.",
    reviewerAvatar: avatarImage("matthew-l-3"),
    date: "2025-10-15T16:30:00Z",
    verified: true,
    helpful: 7,
  },
  {
    id: "rev-082",
    productId: "prod-008",
    rating: 4,
    title: "Solid and stylish",
    content: "Easy to assemble and looks great with our 55-inch TV. The walnut finish is rich and warm. Storage compartments are adequate for a streaming box and game console.",
    reviewerName: "Ryan H.",
    reviewerAvatar: avatarImage("ryan-h-3"),
    date: "2025-09-22T11:00:00Z",
    verified: false,
    helpful: 5,
  },

  // --- prod-016 Platform Bed Frame (3 reviews) ---
  {
    id: "rev-083",
    productId: "prod-016",
    rating: 5,
    title: "Minimal and solid",
    content: "Love the low-profile look. The platform is incredibly solid and there's zero squeak even after months of use. The slats are well-spaced for mattress ventilation.",
    reviewerName: "Brian W.",
    reviewerAvatar: avatarImage("brian-w-2"),
    date: "2025-11-18T10:00:00Z",
    verified: true,
    helpful: 9,
  },
  {
    id: "rev-084",
    productId: "prod-016",
    rating: 4,
    title: "Great value platform bed",
    content: "For the price, this is an excellent platform bed. Simple to assemble and the wood quality is genuine. The only thing missing is a headboard, but we mounted one separately.",
    reviewerName: "Stephanie W.",
    reviewerAvatar: avatarImage("stephanie-w-3"),
    date: "2025-10-08T13:45:00Z",
    verified: true,
    helpful: 6,
  },
  {
    id: "rev-085",
    productId: "prod-016",
    rating: 5,
    title: "Perfect for a guest room",
    content: "Bought this for our guest bedroom and every visitor comments on how comfortable the bed is. The low profile works great in a room with lower ceilings too.",
    reviewerName: "Andrew W.",
    reviewerAvatar: avatarImage("andrew-w-3"),
    date: "2025-08-28T15:00:00Z",
    verified: true,
    helpful: 4,
  },

  // --- prod-026 Counter Height Bar Stool (3 reviews) ---
  {
    id: "rev-086",
    productId: "prod-026",
    rating: 4,
    title: "Stylish counter stools",
    content: "These stools look great at our kitchen island. The plywood seat is comfortable for short stints. For long seating, a cushion would be nice. Build quality is excellent for the price.",
    reviewerName: "Sophia G.",
    reviewerAvatar: avatarImage("sophia-g-4"),
    date: "2025-11-05T10:00:00Z",
    verified: true,
    helpful: 8,
  },
  {
    id: "rev-087",
    productId: "prod-026",
    rating: 5,
    title: "Perfect kitchen island stools",
    content: "Narrow profile fits perfectly under our island with clearance to spare. Easy to assemble and the chrome base is easy to clean. Bought four and they all match perfectly.",
    reviewerName: "Ashley C.",
    reviewerAvatar: avatarImage("ashley-c-3"),
    date: "2025-10-18T14:30:00Z",
    verified: true,
    helpful: 6,
  },
  {
    id: "rev-088",
    productId: "prod-026",
    rating: 4,
    title: "Good stools, slippery at first",
    content: "The plywood seat was a bit slippery at first. After a few weeks of use it developed a bit of grip. Looks-wise they're exactly what we wanted — modern and unobtrusive.",
    reviewerName: "Marcus H.",
    reviewerAvatar: avatarImage("marcus-h-3"),
    date: "2025-09-02T11:30:00Z",
    verified: true,
    helpful: 5,
  },

  // --- prod-030 Oak Sideboard Buffet (2 reviews) ---
  {
    id: "rev-089",
    productId: "prod-030",
    rating: 5,
    title: "Rattan detail is gorgeous",
    content: "The rattan door panels give this sideboard so much character. It's spacious inside with adjustable shelves that fit everything from dinnerware to board games. The oak is beautiful quality.",
    reviewerName: "Hannah S.",
    reviewerAvatar: avatarImage("hannah-s-4"),
    date: "2025-11-22T09:00:00Z",
    verified: true,
    helpful: 10,
  },
  {
    id: "rev-090",
    productId: "prod-030",
    rating: 4,
    title: "Beautiful storage piece",
    content: "We use this as a hallway console and it's perfect. Holds all our table linens, serving dishes, and candles. The rattan panels are a beautiful warm touch against white walls.",
    reviewerName: "Emily C.",
    reviewerAvatar: avatarImage("emily-c-4"),
    date: "2025-10-05T16:00:00Z",
    verified: true,
    helpful: 7,
  },

  // --- prod-035 L-Shaped Desk (2 reviews) ---
  {
    id: "rev-091",
    productId: "prod-035",
    rating: 4,
    title: "Perfect for dual monitors",
    content: "Tons of space for my dual monitor setup, laptop, and all accessories. The cable management tray is a game-changer. Assembly was involved but the instructions are clear.",
    reviewerName: "Tyler A.",
    reviewerAvatar: avatarImage("tyler-a-4"),
    date: "2025-10-30T10:00:00Z",
    verified: true,
    helpful: 9,
  },
  {
    id: "rev-092",
    productId: "prod-035",
    rating: 4,
    title: "Great desk for the price",
    content: "Spacious, well-designed, and sturdy. The keyboard tray slides out smoothly and the grommet holes keep cables organized. Only wish the top was solid wood instead of engineered.",
    reviewerName: "David L.",
    reviewerAvatar: avatarImage("david-l-4"),
    date: "2025-09-15T14:15:00Z",
    verified: true,
    helpful: 6,
  },

  // --- prod-042 Wicker Conversation Set (3 reviews) ---
  {
    id: "rev-093",
    productId: "prod-042",
    rating: 4,
    title: "Great for patio gatherings",
    content: "We love this set for weekend barbecues and evening chats. The Sunbrella cushions have survived multiple rainstorms without any damage. The resin wicker looks like the real thing.",
    reviewerName: "Kevin H.",
    reviewerAvatar: avatarImage("kevin-h-4"),
    date: "2025-11-08T15:00:00Z",
    verified: true,
    helpful: 11,
  },
  {
    id: "rev-094",
    productId: "prod-042",
    rating: 5,
    title: "Outdoor living room",
    content: "This set turned our patio into a true outdoor living room. The loveseat is roomy, the chairs are comfortable, and the coffee table ties everything together. Best outdoor furniture purchase we've made.",
    reviewerName: "Natalie Y.",
    reviewerAvatar: avatarImage("natalie-y-4"),
    date: "2025-10-12T10:30:00Z",
    verified: true,
    helpful: 14,
  },
  {
    id: "rev-095",
    productId: "prod-042",
    rating: 4,
    title: "Well-made but cushion storage needed",
    content: "The furniture itself is excellent quality. Just know you'll want a storage box for the cushions when not in use — even Sunbrella benefits from being stored during harsh weather.",
    reviewerName: "Brandon K.",
    reviewerAvatar: avatarImage("brandon-k-3"),
    date: "2025-09-05T13:45:00Z",
    verified: true,
    helpful: 8,
  },

  // --- prod-047 Ceramic Table Lamp (2 reviews) ---
  {
    id: "rev-096",
    productId: "prod-047",
    rating: 4,
    title: "Beautiful accent lighting",
    content: "The ceramic base has a lovely glaze that catches the light. It provides a warm, ambient glow on our nightstand. The shade is a nice quality linen. Simple, elegant, effective.",
    reviewerName: "Amanda D.",
    reviewerAvatar: avatarImage("amanda-d-4"),
    date: "2025-11-25T10:00:00Z",
    verified: true,
    helpful: 5,
  },
  {
    id: "rev-097",
    productId: "prod-047",
    rating: 5,
    title: "Charming bedside lamp",
    content: "We bought a pair for our nightstands and they're perfect. The warm light creates a cozy atmosphere in the bedroom. Well-proportioned and nicely weighted.",
    reviewerName: "Stephanie W.",
    reviewerAvatar: avatarImage("stephanie-w-4"),
    date: "2025-10-08T16:30:00Z",
    verified: true,
    helpful: 4,
  },

  // --- prod-049 Abstract Canvas Wall Art (2 reviews) ---
  {
    id: "rev-098",
    productId: "prod-049",
    rating: 4,
    title: "Adds warmth to the room",
    content: "The earth tones work perfectly with our neutral palette. The three panels create a dramatic effect on our living room wall. Canvas quality is good and the stretcher bars are solid.",
    reviewerName: "Lauren B.",
    reviewerAvatar: avatarImage("lauren-b-4"),
    date: "2025-11-12T14:00:00Z",
    verified: true,
    helpful: 6,
  },
  {
    id: "rev-099",
    productId: "prod-049",
    rating: 4,
    title: "Nice art, easy to hang",
    content: "Hardware for hanging is included and well-designed — getting the three panels level was straightforward. Colors match the website photos accurately. Good value for ready-to-hang art.",
    reviewerName: "Jason B.",
    reviewerAvatar: avatarImage("jason-b-4"),
    date: "2025-10-01T10:15:00Z",
    verified: true,
    helpful: 3,
  },

  // --- prod-050 Concrete Planter Set (2 reviews) ---
  {
    id: "rev-100",
    productId: "prod-050",
    rating: 5,
    title: "Instagram-worthy planters",
    content: "The speckled finish is so unique and each planter has a slightly different pattern. The graduated sizes look great together on a shelf or windowsill. Drainage holes work perfectly.",
    reviewerName: "Megan T.",
    reviewerAvatar: avatarImage("megan-t-4"),
    date: "2025-11-30T09:00:00Z",
    verified: true,
    helpful: 8,
  },
  {
    id: "rev-101",
    productId: "prod-050",
    rating: 4,
    title: "Cute set, handle with care",
    content: "Love the look of these planters. Just be careful — they're heavier than you'd expect and cement can chip if dropped. The saucers protect surfaces well and the sizes are just right.",
    reviewerName: "Rachel G.",
    reviewerAvatar: avatarImage("rachel-g-3"),
    date: "2025-10-18T15:30:00Z",
    verified: true,
    helpful: 5,
  },

  // --- Additional reviews to reach 105+ total ---
  {
    id: "rev-102",
    productId: "prod-009",
    rating: 5,
    title: "Transforms our bedroom into a retreat",
    content: "The sleeper mechanism is smooth and the mattress is surprisingly comfortable for a sofa bed. Guests always remark on how well they slept. Dual functionality at its best.",
    reviewerName: "Michael T.",
    reviewerAvatar: avatarImage("michael-t-3"),
    date: "2025-11-08T10:30:00Z",
    verified: true,
    helpful: 12,
  },
  {
    id: "rev-103",
    productId: "prod-009",
    rating: 4,
    title: "Great sleeper sofa",
    content: "Finally a sleeper sofa that doesn't look like a sleeper sofa. Stylish during the day and functional at night. The pull-out mechanism takes a bit of getting used to but works well.",
    reviewerName: "Olivia W.",
    reviewerAvatar: avatarImage("olivia-w-4"),
    date: "2025-10-22T14:00:00Z",
    verified: true,
    helpful: 9,
  },
  {
    id: "rev-104",
    productId: "prod-020",
    rating: 5,
    title: "Luxurious canopy bed",
    content: "The canopy frame creates such a dramatic effect in our master bedroom. The black steel is elegant and modern. One of the best furniture purchases we've ever made.",
    reviewerName: "Kayla W.",
    reviewerAvatar: avatarImage("kayla-w-4"),
    date: "2025-11-25T16:00:00Z",
    verified: true,
    helpful: 15,
  },
  {
    id: "rev-105",
    productId: "prod-020",
    rating: 4,
    title: "Statement piece for sure",
    content: "This bed commands attention. The steel frame is rock solid and the proportions are perfect. Assembly required two people and about two hours. Worth every minute.",
    reviewerName: "Robert J.",
    reviewerAvatar: avatarImage("robert-j-4"),
    date: "2025-10-10T11:00:00Z",
    verified: true,
    helpful: 8,
  },
];

// ---- Lookup helpers -------------------------------------------------------

export function getReviewsByProductId(productId: string): Review[] {
  return reviews.filter((r) => r.productId === productId);
}

export function getAverageRating(productId: string): number {
  const productReviews = getReviewsByProductId(productId);
  if (productReviews.length === 0) return 0;
  const sum = productReviews.reduce((acc, r) => acc + r.rating, 0);
  return Math.round((sum / productReviews.length) * 10) / 10;
}

export function getRecentReviews(limit = 10): Review[] {
  return [...reviews]
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, limit);
}
